
#line 3 "lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 306
#define YY_END_OF_BUFFER 307
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[486] =
    {   0,
        0,    0,  307,  306,    3,  287,  305,  306,  306,  303,
      306,  296,  306,  290,  291,  295,  294,  289,  288,  306,
      302,  283,  283,  283,  306,   24,  304,   23,  306,  254,
      256,  258,  260,  262,  272,  282,  264,  270,  282,  282,
      266,  252,  282,  282,  250,  268,  282,  282,  282,  248,
      292,  293,  255,  257,  259,  261,  263,  273,  265,  271,
      282,  267,  253,  282,  282,  251,  269,  282,  282,  282,
      249,  298,    3,   18,    0,    6,    0,  277,  278,  276,
      297,  279,    0,    0,  275,  275,  275,  275,  275,  275,
      283,  283,    0,  284,  280,  281,    0,    0,    1,  300,

       25,   19,   21,  301,  285,  282,  274,  282,  214,  282,
      280,  282,  282,  282,  281,  216,  282,  282,  282,  234,
      282,   52,   60,  218,  228,  282,   56,   54,   58,  230,
      282,  282,  282,  232,  282,   20,   22,  282,  220,   13,
      244,  246,  224,  226,  210,  212,  206,   27,  282,   26,
      238,   17,  282,  236,  208,  282,  282,  242,  240,  282,
      282,  202,  204,  282,  282,  282,  282,  282,  222,  282,
      282,  282,  282,  282,  215,  282,  282,  282,  217,  282,
      282,  282,  235,  282,   53,   61,  219,  229,  282,   57,
       55,   59,  231,  282,  282,  233,  282,  221,  245,  247,

      225,  227,  211,  213,  207,  282,  239,  282,  282,  237,
      209,  282,  282,  243,  241,  282,  282,  203,  205,  282,
      282,  282,  282,  282,  223,  282,  282,  282,  282,  299,
        0,    5,    5,    0,    0,  277,    0,    4,    4,  275,
      275,   30,   34,  275,   33,   31,   32,  275,  275,  275,
      286,  174,  176,  200,  282,  172,  282,  178,  282,  180,
      158,  160,  166,  168,  110,  282,  282,  112,  116,  282,
      184,  282,  282,  282,  282,  188,  190,  192,  122,  124,
      118,  120,  164,  162,  282,  194,  282,  196,  114,  282,
      282,  170,  156,  282,  198,  182,  150,  152,  154,  146,

      148,  144,  142,  140,  138,  136,  132,  134,  130,  128,
      126,  282,  186,  175,  177,  201,  282,  173,  282,  179,
      282,  181,  159,  161,  167,  169,  111,  282,  282,  113,
      117,  185,  282,  189,  191,  193,  123,  125,  119,  121,
      165,  163,  282,  195,  282,  197,  115,  282,  282,  171,
      157,  282,  199,  183,  151,  153,  155,  147,  149,  145,
      143,  141,  139,  137,  133,  135,  131,  129,  127,  282,
      187,    6,    2,  277,    7,  275,  275,   29,   28,  275,
      282,   74,   76,   88,   90,   42,   50,  282,   46,   44,
       48,   72,  282,  282,  282,   94,  282,  282,  282,  282,

       86,   92,   96,   98,  282,  282,   78,   80,   84,   82,
      100,  102,  104,  106,  108,  282,  282,   75,   77,   89,
       91,   43,   51,  282,   47,   45,   49,   73,   95,   87,
       93,   97,   99,  282,  282,   79,   81,   85,   83,  101,
      103,  105,  107,  109,  282,  277,    8,   36,   37,   35,
       38,   39,  275,   70,  282,   16,   62,   12,   14,  282,
      282,  282,   68,  282,   10,   71,  282,   69,  282,   11,
        9,  282,   15,   64,  282,   66,  282,   67,   40,   63,
       41,  282,  282,   65,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   25,
       26,   27,    1,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   39,   50,   51,   52,   53,
       54,    1,   55,    1,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   66,   39,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   39,   77,   78,
       79,   80,    1,   81,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    4,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    3,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1
    } ;

static yyconst flex_uint16_t yy_base[495] =
    {   0,
        0,    0, 1088, 1089,   80, 1089, 1061, 1080,   79,   73,
       65,  104, 1074, 1089, 1089, 1089, 1089, 1089, 1089,   97,
     1089,  121,  138,  157, 1081,   62, 1057,   63,   71,  202,
      247,  163,  179,  206,   86,   98,  133,  222,   74, 1059,
      182, 1058,  259,  239,  266,  270,  274,  124,   73, 1057,
     1089, 1089,  268,  116,  125,  283,  181, 1056,  109,  277,
       92,  141, 1055,  302,  263,  298,  303,  308,  174,  157,
     1054,  995,  256, 1089, 1069, 1068, 1069,  365,  371,  220,
     1089,  386, 1061, 1060,    0, 1018,  380, 1024, 1022, 1030,
      402,  419,  438,  455, 1089, 1089,  474, 1063, 1089, 1089,

     1089, 1089, 1089, 1089,  234,  234, 1089,  264,  316, 1042,
     1041,  224,  290,  180, 1040,  321,   96,  406,  478,  424,
      461,  334,  352,  479, 1039,  252, 1038, 1037, 1036, 1035,
      301,  249,  172,  311,  434, 1034, 1033,  350, 1032,  488,
     1031,  491,  442,  457, 1030, 1029,  494, 1028,  309, 1027,
     1026,  391,  495, 1025,  419,  501,  306, 1024,  365,   75,
      498,  511,  518,  477,  450,  285,  504,  525, 1023,  528,
      506,  514,  509,  521,  547,  530,  402,  533, 1022,  536,
      537,  538,  541,  126, 1021, 1020,  540, 1019,  543, 1018,
     1017, 1016, 1015,  549,  544,  421,  546, 1014, 1013,  556,

      550,  555, 1012, 1011,  563,  559, 1010,  561,  562, 1009,
      567,  566,  560, 1008,  357,  355,  564,  584,  595,  565,
      551,  570,  573,  580, 1007,  602,  613,  574,  569, 1089,
     1023, 1089, 1089, 1025,  572,  643, 1016, 1089, 1089,    0,
      978,    0,    0,  991,    0,    0,    0,  975,  988,  974,
      658,  540,  614, 1089,  611,  998,  627,  997,  630,  629,
      635,  638,  996,  662,  663,  665,  175,  568,  995,  660,
      994,  644,  634,  674,  678,  681,  663,  682,  993,  992,
      991,  990,  685,  690,  693,  989,  695,  988,  987,  691,
      694,  697,  986,  699,  985,  696,  984,  716,  983,  982,

      718,  981,  980,  979,  978,  977,  976,  975,  974,  973,
      972,  702,  971,  970,  969, 1089,  700,  968,  701,  967,
      703,  966,  675,  704,  965,  964,  963,  720,  721,  962,
      961,  960,  723,  959,  726,  727,  958,  957,  956,  955,
      729,  730,  728,  954,  731,  953,  952,  732,  733,  744,
      951,  743,  950,  745,  949,  388,  948,  947,  734,  946,
      945,  944,  943,  942,  941,  940,  939,  938,  937,  746,
      936, 1089, 1089,  795, 1089,  925,  742,    0,    0,  917,
      738,  933,  932,  931,  930,  728,  744,  748,  929,  928,
      927,  926,  739,  772,  753,  925,  785,  788,  797,  735,

      924,  923,  922,  921,  764,  799,  920,  919,  918,  917,
      916,  915,  914,  913,  912,  800,  807,  911,  910,  909,
      907,  902,  897,  808,  892,  879,  874,  871,  870,  869,
      868,  867,  866,  809,  812,  865,  864,  860,  859,  858,
      856,  855,  852,  850,  813, 1089,    0,    0,    0,    0,
        0,    0,  839,  848,  814,  846,  844,  843,  841,  815,
      816,  818,  840,  817,  839,  838,  819,  837,  820,  834,
        0,  821,  833,  759,  822,  737,  825,  645,  633,  829,
      575,  831,  828,  478, 1089,  895,  900,  474,  905,  908,
      913,  918,  923,  926

    } ;

static yyconst flex_int16_t yy_def[495] =
    {   0,
      485,    1,  485,  485,  485,  485,  485,  486,  485,  485,
      485,  485,  487,  485,  485,  485,  485,  485,  485,  488,
      485,  485,  485,  485,  489,  485,  485,  485,  485,  490,
      490,   31,   31,   31,   31,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      485,  485,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  485,  485,  485,  491,  485,  492,  485,  485,  485,
      485,  485,  493,  485,  494,  494,  494,  494,  494,  494,
      485,  485,  485,  485,  485,  485,  485,  489,  485,  485,

      485,  485,  485,  485,  485,   31,  485,   31,   31,  490,
      490,  490,  490,  490,  490,   31,  490,   31,   31,  490,
       31,   31,   31,   31,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  485,
      491,  485,  485,  492,  492,  485,  493,  485,  485,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      485,   31,   31,  485,  490,  490,  490,  490,  490,   31,
      490,  490,  490,   31,   31,   31,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  485,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  485,  485,  485,  485,  494,  494,  494,  494,  494,
      490,  490,  490,  490,  490,   31,   31,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  485,  494,  494,  494,  494,
      494,  494,  494,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      494,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,    0,  485,  485,  485,  485,  485,
      485,  485,  485,  485

    } ;

static yyconst flex_uint16_t yy_nxt[1171] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,    4,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   40,   46,   47,   48,   40,   40,
       49,   40,   50,   51,   52,    4,   53,   54,   55,   56,
       57,   58,   40,   59,   60,   61,   62,   63,   64,   65,
       66,   40,   67,   68,   69,   40,   40,   70,   40,   71,
       72,   73,   77,   73,   80,   80,  100,  101,  103,  104,
      105,  105,   79,   79,   79,  107,  107,  107,   78,   78,

       78,   79,   79,   79,   79,   79,   79,   78,   78,   78,
       78,   78,   78,   81,  107,  173,  106,  145,  107,  146,
      107,  294,  110,   82,   82,   82,   86,  135,   87,   88,
      136,  107,   82,   82,   82,   82,   82,   82,  107,   89,
       91,   91,   92,  258,   90,  137,  107,  107,  107,   93,
       94,   93,   93,   93,   93,  107,   95,   91,   91,   92,
      172,  138,  203,  107,  204,  197,   93,   94,   93,   93,
       93,   93,  139,   95,  179,  198,   92,   92,   92,  107,
      180,  181,  326,  182,   96,   93,   93,   93,   93,   93,
       93,  118,   95,  119,  107,  183,  107,  107,   97,  110,

      205,   96,  107,  107,  107,  206,  120,  121,  122,  106,
      123,  124,  257,  147,  148,  125,  126,  270,  149,  127,
       96,  106,  106,  106,  107,  128,  229,  392,  129,  150,
      106,  106,  106,  108,  106,  109,  106,  111,  228,   80,
       80,  112,  130,  113,  107,  193,  107,  131,  114,  194,
      132,  133,  195,  105,  105,  140,  134,   73,  196,   73,
      255,  107,  141,  142,  106,  115,  106,  106,  106,  107,
      110,  107,  143,  144,  107,  106,  106,  116,  106,  106,
      106,  107,  111,  117,  155,  107,  156,  157,  107,  151,
      107,  152,  107,  267,  252,  253,  107,  269,  158,  107,

      110,  153,  161,  165,  166,  107,  167,  107,  159,  162,
      115,  154,  107,  168,  160,  163,  164,  169,  305,  170,
      107,  256,  171,  107,  107,  107,  254,  174,  107,  175,
      107,  107,  268,  107,  176,  211,  177,  212,  213,  184,
      185,  178,  186,  187,  199,  200,  106,  188,  189,  285,
      190,  106,  110,  292,  201,  202,  191,  110,  214,  192,
      207,  271,  208,  217,  106,  221,  222,  215,  223,  218,
      110,  209,  107,  216,  224,  219,  220,  107,  225,  107,
      226,  210,  106,  227,  236,  236,  236,  107,  110,  273,
       79,   79,   79,  236,  236,  236,  236,  236,  236,   79,

       79,   79,   79,   79,   79,   82,   82,   82,  293,  242,
      107,  243,  244,  107,   82,   82,   82,   82,   82,   82,
      245,   91,   91,   92,  107,  286,  246,  351,  352,  247,
       93,   94,   93,   93,   93,   93,  106,   95,   92,   92,
       92,  107,  110,  107,  443,  259,  107,   93,   93,   93,
       93,   93,   93,  289,   95,  261,  107,   93,   93,   93,
      262,  318,  272,  263,  107,   96,   93,   93,   93,   93,
       93,   93,  107,   95,   93,   93,   93,  279,   85,  107,
      304,  280,   96,   93,   93,   93,   93,   93,   93,  264,
       95,  106,  281,  251,  251,  251,  282,  110,  332,  107,

      107,   96,  251,  251,  251,  251,  251,  251,  106,  265,
      107,  260,  266,  107,  110,  110,  107,  107,   96,  274,
      107,  276,  277,  107,  303,  283,  107,  278,  107,  275,
      284,  107,  290,  107,  287,  311,  107,  291,  288,  297,
      107,  298,  299,  107,  295,  296,  300,  107,  301,  302,
      107,  306,  107,  307,  313,  107,  309,  316,  107,  107,
      107,  312,  107,  107,  308,  107,  107,  310,  107,  107,
      106,  107,  107,  107,  373,  235,  110,  107,  107,  314,
      315,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  319,  317,  107,  107,  107,  327,  322,

      323,  328,  107,  321,  393,  324,  107,  325,  330,  362,
      320,  329,  333,  337,  334,  335,  338,  107,  339,  331,
      336,  340,  341,  344,  107,  348,  343,  342,  345,  347,
      349,  363,  346,  107,  350,  107,  365,  353,  354,  361,
      355,  371,  356,  357,  106,  381,  366,  364,  370,  107,
      110,  358,  107,  359,  360,  107,  107,  107,  367,  106,
      107,  382,  374,  374,  374,  110,  107,  107,  368,  383,
      369,  374,  374,  374,  374,  374,  374,  251,  251,  251,
      384,  396,  107,  385,  395,  107,  251,  251,  251,  251,
      251,  251,  106,  106,  386,  387,  107,  107,  110,  110,

      107,  388,  394,  107,  107,  389,  397,  107,  401,  398,
      399,  390,  107,  107,  391,  107,  107,  107,  107,  107,
      400,  107,  107,  107,  107,  107,  107,  402,  409,  405,
      403,  406,  412,  410,  411,  404,  407,  413,  107,  408,
      107,  416,  107,  107,  414,  107,  415,  420,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  106,  107,
      107,  107,  417,  418,  110,  107,  107,  107,  107,  419,
      107,  448,  456,  449,  106,  107,  421,  422,  423,  454,
      110,  107,  450,  462,  424,  458,  107,  425,  451,  455,
      444,  452,  434,  426,  107,  435,  427,  429,  430,  431,

      428,  432,  433,  438,  436,  437,  440,  107,  439,  441,
      107,  463,  445,  442,  446,  446,  446,  457,  459,  107,
      460,  107,  107,  446,  446,  446,  446,  446,  446,  107,
      107,  107,  465,  461,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  464,  472,  107,  473,  475,
      107,  107,  479,  107,  480,  107,  107,  474,  482,  107,
      107,  107,  107,  107,  476,  107,  107,  483,  107,  484,
      107,  471,  107,  470,  107,  466,  467,  107,  107,  477,
      107,  107,  107,  468,  481,  469,  107,  107,  107,  107,
      107,  107,  107,  107,  478,   75,  107,   75,   75,   75,

       83,  107,   83,   83,   83,   98,   98,   98,   98,   98,
      110,  110,  110,  231,  107,  231,  231,  231,  234,  107,
      234,  234,  234,  237,  107,  237,  237,  237,  240,  107,
      240,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  453,  447,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,

      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  380,  379,  378,  377,  376,  375,  373,  372,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,   99,  250,  249,  248,  241,
      239,  238,  235,  233,  232,  230,  107,  107,  107,  107,
      107,  107,  102,   99,   84,   76,   74,  485,    3,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485
    } ;

static yyconst flex_int16_t yy_chk[1171] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    9,    5,   11,   11,   26,   26,   28,   28,
       29,   29,   10,   10,   10,   49,   39,  160,    9,    9,

        9,   10,   10,   10,   10,   10,   10,    9,    9,    9,
        9,    9,    9,   12,   61,   49,   35,   39,  117,   39,
       36,  160,   35,   12,   12,   12,   20,   35,   20,   20,
       36,   59,   12,   12,   12,   12,   12,   12,   54,   20,
       22,   22,   22,  117,   20,   36,   48,   55,  184,   22,
       22,   22,   22,   22,   22,   37,   22,   23,   23,   23,
       48,   37,   61,   62,   61,   59,   23,   23,   23,   23,
       23,   23,   37,   23,   54,   59,   24,   24,   24,   70,
       54,   55,  184,   55,   22,   24,   24,   24,   24,   24,
       24,   32,   24,   32,  133,   55,   69,  267,   22,   32,

       62,   23,  114,   57,   41,   62,   32,   33,   33,   33,
       33,   33,  114,   41,   41,   33,   33,  133,   41,   33,
       24,   30,   30,   30,   30,   33,   70,  267,   33,   41,
       30,   30,   30,   30,   30,   30,   34,   30,   69,   80,
       80,   30,   34,   30,   38,   57,  112,   34,   30,   57,
       34,   34,   57,  105,  105,   38,   34,   73,   57,   73,
      112,   44,   38,   38,  106,   30,   31,   31,   31,   31,
      106,  132,   38,   38,  126,   31,   31,   31,   31,   31,
       31,   43,   31,   31,   44,   65,   44,   44,   45,   43,
       53,   43,   46,  126,  108,  108,   47,  132,   45,   60,

      108,   43,   46,   47,   47,   56,   47,  166,   45,   46,
       31,   43,  113,   47,   45,   46,   46,   47,  166,   47,
       66,  113,   47,  131,   64,   67,  109,   53,  157,   53,
       68,  149,  131,  134,   53,   65,   53,   65,   65,   56,
       56,   53,   56,   56,   60,   60,  109,   56,   56,  149,
       56,  116,  109,  157,   60,   60,   56,  116,   66,   56,
       64,  134,   64,   67,  122,   68,   68,   66,   68,   67,
      122,   64,  138,   66,   68,   67,   67,  216,   68,  215,
       68,   64,  123,   68,   78,   78,   78,  159,  123,  138,
       79,   79,   79,   78,   78,   78,   78,   78,   78,   79,

       79,   79,   79,   79,   79,   82,   82,   82,  159,   87,
      356,   87,   87,  152,   82,   82,   82,   82,   82,   82,
       87,   91,   91,   91,  177,  152,   87,  215,  216,   87,
       91,   91,   91,   91,   91,   91,  118,   91,   92,   92,
       92,  155,  118,  196,  356,  118,  120,   92,   92,   92,
       92,   92,   92,  155,   92,  120,  135,   93,   93,   93,
      120,  177,  135,  120,  143,   91,   93,   93,   93,   93,
       93,   93,  165,   93,   94,   94,   94,  143,  488,  144,
      165,  143,   92,   94,   94,   94,   94,   94,   94,  121,
       94,  121,  144,   97,   97,   97,  144,  121,  196,  164,

      484,   93,   97,   97,   97,   97,   97,   97,  119,  124,
      140,  119,  124,  142,  119,  124,  147,  153,   94,  140,
      161,  142,  142,  156,  164,  147,  167,  142,  171,  140,
      147,  173,  156,  162,  153,  171,  172,  156,  153,  162,
      163,  162,  162,  174,  161,  161,  163,  168,  163,  163,
      170,  167,  176,  168,  173,  178,  170,  175,  180,  181,
      182,  172,  187,  183,  168,  189,  195,  170,  197,  175,
      252,  194,  201,  221,  235,  235,  252,  202,  200,  174,
      174,  206,  213,  208,  209,  205,  217,  220,  212,  211,
      268,  229,  222,  178,  176,  223,  228,  481,  187,  182,

      183,  187,  224,  181,  268,  183,  218,  183,  194,  221,
      180,  189,  197,  201,  200,  200,  201,  219,  202,  195,
      200,  202,  205,  208,  226,  212,  206,  205,  209,  211,
      212,  222,  209,  255,  213,  227,  224,  217,  217,  220,
      218,  229,  218,  218,  253,  255,  224,  223,  228,  257,
      253,  219,  259,  219,  219,  479,  273,  261,  226,  260,
      262,  257,  236,  236,  236,  260,  272,  478,  226,  259,
      227,  236,  236,  236,  236,  236,  236,  251,  251,  251,
      261,  273,  270,  262,  272,  277,  251,  251,  251,  251,
      251,  251,  264,  265,  266,  266,  274,  323,  264,  265,

      275,  266,  270,  276,  278,  266,  274,  283,  277,  275,
      276,  266,  284,  290,  266,  285,  291,  287,  296,  292,
      276,  294,  317,  319,  312,  321,  324,  278,  292,  285,
      283,  287,  296,  292,  294,  284,  290,  296,  298,  291,
      301,  312,  328,  329,  298,  333,  301,  323,  335,  336,
      343,  341,  342,  345,  348,  349,  359,  400,  386,  476,
      381,  393,  317,  319,  386,  352,  350,  354,  370,  321,
      388,  377,  393,  377,  387,  395,  324,  328,  328,  381,
      387,  474,  377,  400,  328,  395,  405,  328,  377,  388,
      359,  377,  343,  328,  394,  345,  328,  333,  335,  336,

      329,  341,  342,  350,  348,  349,  352,  397,  350,  354,
      398,  405,  370,  354,  374,  374,  374,  394,  397,  399,
      398,  406,  416,  374,  374,  374,  374,  374,  374,  417,
      424,  434,  416,  399,  435,  445,  455,  460,  461,  464,
      462,  467,  469,  472,  475,  406,  455,  477,  460,  462,
      483,  480,  472,  482,  475,  473,  470,  461,  480,  468,
      466,  465,  463,  459,  464,  458,  457,  482,  456,  483,
      454,  453,  444,  445,  443,  417,  424,  442,  441,  467,
      440,  439,  438,  434,  477,  435,  437,  436,  433,  432,
      431,  430,  429,  428,  469,  486,  427,  486,  486,  486,

      487,  426,  487,  487,  487,  489,  489,  489,  489,  489,
      490,  490,  490,  491,  425,  491,  491,  491,  492,  423,
      492,  492,  492,  493,  422,  493,  493,  493,  494,  421,
      494,  420,  419,  418,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  404,  403,  402,  401,  396,  392,  391,
      390,  389,  385,  384,  383,  382,  380,  376,  371,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  358,
      357,  355,  353,  351,  347,  346,  344,  340,  339,  338,
      337,  334,  332,  331,  330,  327,  326,  325,  322,  320,
      318,  315,  314,  313,  311,  310,  309,  308,  307,  306,

      305,  304,  303,  302,  300,  299,  297,  295,  293,  289,
      288,  286,  282,  281,  280,  279,  271,  269,  263,  258,
      256,  250,  249,  248,  244,  241,  237,  234,  231,  225,
      214,  210,  207,  204,  203,  199,  198,  193,  192,  191,
      190,  188,  186,  185,  179,  169,  158,  154,  151,  150,
      148,  146,  145,  141,  139,  137,  136,  130,  129,  128,
      127,  125,  115,  111,  110,   98,   90,   89,   88,   86,
       84,   83,   77,   76,   75,   72,   71,   63,   58,   50,
       42,   40,   27,   25,   13,    8,    7,    3,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"

#include <stdio.h>
#include <string.h>


#include "grammar.h"


/* Externally defined functions used here */
extern void fatalError(const char *str);


/* Declarations of locally defined functions */
void reset_lexer();
int from_binary(const char * s);


/*****************************/
/* Locally defined functions */
void reset_lexer() { YY_FLUSH_BUFFER;  yylineno = 1; }

int from_binary(const char * s) {
 char aux[60];
 
  if (strlen(s) > 59) { fatalError("Binary is too long"); }  
  strncpy(aux,s,strlen(s)); aux[strlen(s)] = 0x0;
  if (aux[strlen(aux)-1] == 'B' || aux[strlen(aux)-1] == 'b') {
     aux[strlen(aux)-1] = 0x0;
  }
  return (int) strtol(aux, NULL, 2);

}

int from_hexa(const char * s) {
 char aux[60];

  if (strlen(s) > 59) { fatalError("Hexadecimal number is too long"); }   
  strncpy(aux,s,strlen(s)); aux[strlen(s)] = 0x0;
  if (aux[strlen(aux)-1] == 'H' || aux[strlen(aux)-1] == 'h') {
     aux[strlen(aux)-1] = 0x0;
  }
  return (int) strtol(aux, NULL, 16);

}


#define YY_NO_INPUT 1
#line 920 "lex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 53 "lex.l"

#line 1138 "lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 486 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1089 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 54 "lex.l"
{ return NEWLINE; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 55 "lex.l"
{  return NEWLINE; } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "lex.l"
/* eat up whitespace */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "lex.l"
{ yylval.normal = yytext[1]; return CHAR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "lex.l"
{ yylval.normal = yytext[1]; return CHAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "lex.l"
{  strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-2]=0x0;return STRING; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "lex.l"
{  strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-2]=0x0;return STRING; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "lex.l"
{ return DEFB; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "lex.l"
{ return TITLE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "lex.l"
{ return TITLE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "lex.l"
{ return TITLE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "lex.l"
{ return FNAME; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "lex.l"
{ return IF; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "lex.l"
{ return IFDEF; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "lex.l"
{ return IFNDEF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "lex.l"
{ return ENDIF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "lex.l"
{ return NEQUAL;  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "lex.l"
{ return NEQUAL;  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "lex.l"
{ return EQUAL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "lex.l"
{ return GREATEREQ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "lex.l"
{ return GREATEREQ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "lex.l"
{ return GREATERTHAN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "lex.l"
{ return GREATERTHAN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "lex.l"
{ return LESSTHAN;    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "lex.l"
{ return LESSEQ; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "lex.l"
{ return LESSTHAN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "lex.l"
{ return LESSEQ; } 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "lex.l"
{ return ORG; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "lex.l"
{ return EQU;  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "lex.l"
{ return DEFB; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "lex.l"
{ return DEFS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "lex.l"
{ return DEFW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "lex.l"
{ return DEFB; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "lex.l"
{ return DEFD; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "lex.l"
{ return DEFB; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lex.l"
{ return DEFB; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "lex.l"
{ return DEFD; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "lex.l"
{ return DEFS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "lex.l"
{ return DEFW; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "lex.l"
{ return DEFINED; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "lex.l"
{ return DEFINED; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "lex.l"
{ return DEFB; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "lex.l"
{ return DEFB; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 97 "lex.l"
{ return DEFS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 98 "lex.l"
{ return DEFS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "lex.l"
{ return DEFB; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "lex.l"
{ return DEFB; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "lex.l"
{ return DEFW; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "lex.l"
{ return DEFW; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "lex.l"
{ return DEFC; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "lex.l"
{ return DEFC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "lex.l"
{ return DEFB; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "lex.l"
{ return DEFB; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "lex.l"
{ return DEFS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "lex.l"
{ return DEFS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "lex.l"
{ return DEFB; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "lex.l"
{ return DEFB; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "lex.l"
{ return DEFW; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "lex.l"
{ return DEFW; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "lex.l"
{ return DEFD; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "lex.l"
{ return DEFD; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "lex.l"
{ return ERROR; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "lex.l"
{ return INCLUDE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "lex.l"
{ return INCLUDEBIN;  }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "lex.l"
{ return INCLUDEBIN;  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "lex.l"
{ return NOLIST; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 120 "lex.l"
{ return NOLIST; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "lex.l"
{ return LIMIT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 122 "lex.l"
{ return LIMIT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 123 "lex.l"
{ return ALIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "lex.l"
{ return ALIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "lex.l"
{ return DJNZ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "lex.l"
{ return DJNZ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 127 "lex.l"
{ return ASEG; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "lex.l"
{ return ASEG; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "lex.l"
{ return CALL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "lex.l"
{ return CALL; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "lex.l"
{ return OTDR; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "lex.l"
{ return OTDR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "lex.l"
{ return OTIR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "lex.l"
{ return OTIR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "lex.l"
{ return OUTI; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "lex.l"
{ return OUTI; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "lex.l"
{ return OUTD; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "lex.l"
{ return OUTD; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "lex.l"
{ return INDR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "lex.l"
{ return INDR; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "lex.l"
{ return CPDR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "lex.l"
{ return CPDR; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "lex.l"
{ return CPIR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "lex.l"
{ return CPIR; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "lex.l"
{ return INIR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "lex.l"
{ return INIR; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "lex.l"
{ return HALT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "lex.l"
{ return HALT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "lex.l"
{ return LDDR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "lex.l"
{ return LDDR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "lex.l"
{ return LDIR; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "lex.l"
{ return LDIR; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "lex.l"
{ return PUSH; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "lex.l"
{ return PUSH; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "lex.l"
{ return RETI; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 156 "lex.l"
{ return RETI; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "lex.l"
{ return RETN; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "lex.l"
{ return RETN; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "lex.l"
{ return RLCA; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "lex.l"
{ return RLCA; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 161 "lex.l"
{ return RRCA; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 162 "lex.l"
{ return RRCA; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 163 "lex.l"
{ return DEC; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 164 "lex.l"
{ return DEC; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 165 "lex.l"
{ return END; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 166 "lex.l"
{ return END; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 167 "lex.l"
{ return ORG; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 168 "lex.l"
{ return ORG; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 169 "lex.l"
{ return EQU; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 170 "lex.l"
{ return EQU; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 171 "lex.l"
{ return IYH; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 172 "lex.l"
{ return IYH; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 173 "lex.l"
{ return IYL; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 174 "lex.l"
{ return IYL; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 175 "lex.l"
{ return IXH; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 176 "lex.l"
{ return IXH; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 177 "lex.l"
{ return IXL; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 178 "lex.l"
{ return IXL; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 179 "lex.l"
{ return SUB; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 180 "lex.l"
{ return SUB; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 181 "lex.l"
{ return SRL; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 182 "lex.l"
{ return SRL; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 183 "lex.l"
{ return SRA; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 184 "lex.l"
{ return SRA; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 185 "lex.l"
{ return SLA; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 186 "lex.l"
{ return SLA; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 187 "lex.l"
{ return SLL; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 188 "lex.l"
{ return SLL; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 189 "lex.l"
{ return SET; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 190 "lex.l"
{ return SET; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 191 "lex.l"
{ return SCF; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 192 "lex.l"
{ return SCF; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 193 "lex.l"
{ return SBC; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 194 "lex.l"
{ return SBC; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 195 "lex.l"
{ return RST; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 196 "lex.l"
{ return RST; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 197 "lex.l"
{ return RRD; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 198 "lex.l"
{ return RRD; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 199 "lex.l"
{ return RRA; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 200 "lex.l"
{ return RRA; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 201 "lex.l"
{ return RRC; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 202 "lex.l"
{ return RRC; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 203 "lex.l"
{ return RLA; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 204 "lex.l"
{ return RLA; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 205 "lex.l"
{ return RLC; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 206 "lex.l"
{ return RLC; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 207 "lex.l"
{ return RLD; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 208 "lex.l"
{ return RLD; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 209 "lex.l"
{ return POP; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 210 "lex.l"
{ return POP; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 211 "lex.l"
{ return CPD; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 212 "lex.l"
{ return CPD; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 213 "lex.l"
{ return CPI; }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 214 "lex.l"
{ return CPI; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 215 "lex.l"
{ return LDI; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 216 "lex.l"
{ return LDI; }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 217 "lex.l"
{ return LDD; }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 218 "lex.l"
{ return LDD; }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 219 "lex.l"
{ return CPL; }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 220 "lex.l"
{ return CPL; }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 221 "lex.l"
{ return DAA; }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 222 "lex.l"
{ return DAA; }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 223 "lex.l"
{ return OUT; }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 224 "lex.l"
{ return OUT; }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 225 "lex.l"
{ return AND; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 226 "lex.l"
{ return AND; }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 227 "lex.l"
{ return ADC; }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 228 "lex.l"
{ return ADC; }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 229 "lex.l"
{ return ADD; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 230 "lex.l"
{ return ADD; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 231 "lex.l"
{ return BIT; }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 232 "lex.l"
{ return BIT; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 233 "lex.l"
{ return CCF; }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 234 "lex.l"
{ return CCF; }
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 235 "lex.l"
{ return RET; }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 236 "lex.l"
{ return RET; }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 237 "lex.l"
{ return EXX; }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 238 "lex.l"
{ return EXX; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 239 "lex.l"
{ return XOR; }
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 240 "lex.l"
{ return XOR; }
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 241 "lex.l"
{ return INC; }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 242 "lex.l"
{ return INC; }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 243 "lex.l"
{ return IND; }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 244 "lex.l"
{ return IND; }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 245 "lex.l"
{ return INI; }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 246 "lex.l"
{ return INI; }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 247 "lex.l"
{ return NEG; }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 248 "lex.l"
{ return NEG; }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 249 "lex.l"
{ return NOP; }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 250 "lex.l"
{ return NOP; }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 251 "lex.l"
{ return RES; }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 252 "lex.l"
{ return RES; }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 253 "lex.l"
{ return AFPLUS; }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 254 "lex.l"
{ return AFPLUS; }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 255 "lex.l"
{ return RL; }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 256 "lex.l"
{ return RL; }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 257 "lex.l"
{ return RR; }
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 258 "lex.l"
{ return RR; }
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 259 "lex.l"
{ return LD; }
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 260 "lex.l"
{ return LD; }
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 261 "lex.l"
{ return OR; }
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 262 "lex.l"
{ return OR; }
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 263 "lex.l"
{ return JP; }
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 264 "lex.l"
{ return JP; }
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 265 "lex.l"
{ return JR; }
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 266 "lex.l"
{ return JR; }
	YY_BREAK
case 214:
YY_RULE_SETUP
#line 267 "lex.l"
{ return AF; }
	YY_BREAK
case 215:
YY_RULE_SETUP
#line 268 "lex.l"
{ return AF; }
	YY_BREAK
case 216:
YY_RULE_SETUP
#line 269 "lex.l"
{ return BC; }
	YY_BREAK
case 217:
YY_RULE_SETUP
#line 270 "lex.l"
{ return BC; }
	YY_BREAK
case 218:
YY_RULE_SETUP
#line 271 "lex.l"
{ return DE; }
	YY_BREAK
case 219:
YY_RULE_SETUP
#line 272 "lex.l"
{ return DE; }
	YY_BREAK
case 220:
YY_RULE_SETUP
#line 273 "lex.l"
{ return HL; }
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 274 "lex.l"
{ return HL; }
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 275 "lex.l"
{ return SP; }
	YY_BREAK
case 223:
YY_RULE_SETUP
#line 276 "lex.l"
{ return SP; }
	YY_BREAK
case 224:
YY_RULE_SETUP
#line 277 "lex.l"
{ return IX; }
	YY_BREAK
case 225:
YY_RULE_SETUP
#line 278 "lex.l"
{ return IX; }
	YY_BREAK
case 226:
YY_RULE_SETUP
#line 279 "lex.l"
{ return IY; }
	YY_BREAK
case 227:
YY_RULE_SETUP
#line 280 "lex.l"
{ return IY; }
	YY_BREAK
case 228:
YY_RULE_SETUP
#line 281 "lex.l"
{ return DI; }
	YY_BREAK
case 229:
YY_RULE_SETUP
#line 282 "lex.l"
{ return DI; }
	YY_BREAK
case 230:
YY_RULE_SETUP
#line 283 "lex.l"
{ return EI; }
	YY_BREAK
case 231:
YY_RULE_SETUP
#line 284 "lex.l"
{ return EI; }
	YY_BREAK
case 232:
YY_RULE_SETUP
#line 285 "lex.l"
{ return EX; }
	YY_BREAK
case 233:
YY_RULE_SETUP
#line 286 "lex.l"
{ return EX; }
	YY_BREAK
case 234:
YY_RULE_SETUP
#line 287 "lex.l"
{ return CP; }
	YY_BREAK
case 235:
YY_RULE_SETUP
#line 288 "lex.l"
{ return CP; }
	YY_BREAK
case 236:
YY_RULE_SETUP
#line 289 "lex.l"
{ return NZ; }
	YY_BREAK
case 237:
YY_RULE_SETUP
#line 290 "lex.l"
{ return NZ; }
	YY_BREAK
case 238:
YY_RULE_SETUP
#line 291 "lex.l"
{ return NC; }
	YY_BREAK
case 239:
YY_RULE_SETUP
#line 292 "lex.l"
{ return NC; }
	YY_BREAK
case 240:
YY_RULE_SETUP
#line 293 "lex.l"
{ return PO; }
	YY_BREAK
case 241:
YY_RULE_SETUP
#line 294 "lex.l"
{ return PO; }
	YY_BREAK
case 242:
YY_RULE_SETUP
#line 295 "lex.l"
{ return PE; }
	YY_BREAK
case 243:
YY_RULE_SETUP
#line 296 "lex.l"
{ return PE; }
	YY_BREAK
case 244:
YY_RULE_SETUP
#line 297 "lex.l"
{ return IM; }
	YY_BREAK
case 245:
YY_RULE_SETUP
#line 298 "lex.l"
{ return IM; }
	YY_BREAK
case 246:
YY_RULE_SETUP
#line 299 "lex.l"
{ return IN; }
	YY_BREAK
case 247:
YY_RULE_SETUP
#line 300 "lex.l"
{ return IN; }
	YY_BREAK
case 248:
YY_RULE_SETUP
#line 301 "lex.l"
{ return Z; }
	YY_BREAK
case 249:
YY_RULE_SETUP
#line 302 "lex.l"
{ return Z; }
	YY_BREAK
case 250:
YY_RULE_SETUP
#line 303 "lex.l"
{ return P; }
	YY_BREAK
case 251:
YY_RULE_SETUP
#line 304 "lex.l"
{ return P; }
	YY_BREAK
case 252:
YY_RULE_SETUP
#line 305 "lex.l"
{ return M; }
	YY_BREAK
case 253:
YY_RULE_SETUP
#line 306 "lex.l"
{ return M; }
	YY_BREAK
case 254:
YY_RULE_SETUP
#line 307 "lex.l"
{ return A; }
	YY_BREAK
case 255:
YY_RULE_SETUP
#line 308 "lex.l"
{ return A; }
	YY_BREAK
case 256:
YY_RULE_SETUP
#line 309 "lex.l"
{ return B; }
	YY_BREAK
case 257:
YY_RULE_SETUP
#line 310 "lex.l"
{ return B; }
	YY_BREAK
case 258:
YY_RULE_SETUP
#line 311 "lex.l"
{ return C; }
	YY_BREAK
case 259:
YY_RULE_SETUP
#line 312 "lex.l"
{ return C; }
	YY_BREAK
case 260:
YY_RULE_SETUP
#line 313 "lex.l"
{ return D; }
	YY_BREAK
case 261:
YY_RULE_SETUP
#line 314 "lex.l"
{ return D; }
	YY_BREAK
case 262:
YY_RULE_SETUP
#line 315 "lex.l"
{ return E; }
	YY_BREAK
case 263:
YY_RULE_SETUP
#line 316 "lex.l"
{ return E; }
	YY_BREAK
case 264:
YY_RULE_SETUP
#line 317 "lex.l"
{ return H; }
	YY_BREAK
case 265:
YY_RULE_SETUP
#line 318 "lex.l"
{ return H; }
	YY_BREAK
case 266:
YY_RULE_SETUP
#line 319 "lex.l"
{ return L; }
	YY_BREAK
case 267:
YY_RULE_SETUP
#line 320 "lex.l"
{ return L; }
	YY_BREAK
case 268:
YY_RULE_SETUP
#line 321 "lex.l"
{ return R; }
	YY_BREAK
case 269:
YY_RULE_SETUP
#line 322 "lex.l"
{ return R; }
	YY_BREAK
case 270:
YY_RULE_SETUP
#line 323 "lex.l"
{ return I; }
	YY_BREAK
case 271:
YY_RULE_SETUP
#line 324 "lex.l"
{ return I; }
	YY_BREAK
case 272:
YY_RULE_SETUP
#line 325 "lex.l"
{ return F; }
	YY_BREAK
case 273:
YY_RULE_SETUP
#line 326 "lex.l"
{ return F; }
	YY_BREAK
case 274:
YY_RULE_SETUP
#line 327 "lex.l"
{ strncpy(yylval.literal,yytext,strlen(yytext)); yylval.literal[strlen(yytext)-1]=0x0;return LABEL; }
	YY_BREAK
case 275:
YY_RULE_SETUP
#line 328 "lex.l"
{ strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-1]=0x0;return LABEL; }
	YY_BREAK
case 276:
YY_RULE_SETUP
#line 329 "lex.l"
{ yylval.normal = from_binary(yytext+1); return INTEGER; }
	YY_BREAK
case 277:
YY_RULE_SETUP
#line 330 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 278:
YY_RULE_SETUP
#line 331 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 279:
YY_RULE_SETUP
#line 332 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 280:
YY_RULE_SETUP
#line 333 "lex.l"
{ yylval.normal = from_hexa(yytext); return INTEGER;  }
	YY_BREAK
case 281:
YY_RULE_SETUP
#line 334 "lex.l"
{ yylval.normal = from_hexa(yytext); return INTEGER;  }
	YY_BREAK
case 282:
YY_RULE_SETUP
#line 335 "lex.l"
{ strcpy(yylval.literal,yytext); return LITERAL; }
	YY_BREAK
case 283:
YY_RULE_SETUP
#line 336 "lex.l"
{ yylval.normal = atoi(yytext); return INTEGER; }
	YY_BREAK
case 284:
YY_RULE_SETUP
#line 337 "lex.l"
{ yylval.normal = from_binary(yytext); return INTEGER;  }
	YY_BREAK
case 285:
YY_RULE_SETUP
#line 338 "lex.l"
{ yylval.normal = from_binary(yytext+1); return INTEGER;  }
	YY_BREAK
case 286:
YY_RULE_SETUP
#line 339 "lex.l"
{ yylval.normal = from_hexa(yytext+2); return INTEGER; }
	YY_BREAK
case 287:
/* rule 287 can match eol */
YY_RULE_SETUP
#line 340 "lex.l"
{ return NEWLINE; }
	YY_BREAK
case 288:
YY_RULE_SETUP
#line 341 "lex.l"
{ return MINUS; }
	YY_BREAK
case 289:
YY_RULE_SETUP
#line 342 "lex.l"
{ return COMMA; }
	YY_BREAK
case 290:
YY_RULE_SETUP
#line 343 "lex.l"
{ return PARLEFT; }
	YY_BREAK
case 291:
YY_RULE_SETUP
#line 344 "lex.l"
{ return PARRIGHT; }
	YY_BREAK
case 292:
YY_RULE_SETUP
#line 345 "lex.l"
{ return PARLEFT; }
	YY_BREAK
case 293:
YY_RULE_SETUP
#line 346 "lex.l"
{ return PARRIGHT; }
	YY_BREAK
case 294:
YY_RULE_SETUP
#line 347 "lex.l"
{ return PLUS; }
	YY_BREAK
case 295:
YY_RULE_SETUP
#line 348 "lex.l"
{ return MULT; }
	YY_BREAK
case 296:
YY_RULE_SETUP
#line 349 "lex.l"
{ return BITAND; }
	YY_BREAK
case 297:
YY_RULE_SETUP
#line 350 "lex.l"
{ return AND; }
	YY_BREAK
case 298:
YY_RULE_SETUP
#line 351 "lex.l"
{ return BITOR;  }
	YY_BREAK
case 299:
YY_RULE_SETUP
#line 352 "lex.l"
{ return OR;  }
	YY_BREAK
case 300:
YY_RULE_SETUP
#line 353 "lex.l"
{ return OPSHLF; }
	YY_BREAK
case 301:
YY_RULE_SETUP
#line 354 "lex.l"
{ return OPSHRT; }
	YY_BREAK
case 302:
YY_RULE_SETUP
#line 355 "lex.l"
{ return DIVIDE; }
	YY_BREAK
case 303:
YY_RULE_SETUP
#line 356 "lex.l"
{ return DOLAR;  }
	YY_BREAK
case 304:
YY_RULE_SETUP
#line 357 "lex.l"
{ return EQUAL;  }
	YY_BREAK
case 305:
YY_RULE_SETUP
#line 358 "lex.l"
{ return EXCLAMATION; }
	YY_BREAK
case 306:
YY_RULE_SETUP
#line 360 "lex.l"
ECHO;
	YY_BREAK
#line 2728 "lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 486 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 486 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 485);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 360 "lex.l"




