
#line 2 "lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 291
#define YY_END_OF_BUFFER 292
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[433] =
    {   0,
        0,    0,  292,  291,    1,  272,  290,  291,  291,  288,
      291,  281,  291,  275,  276,  280,  279,  274,  273,  291,
      287,  268,  268,  268,   18,  289,   17,  291,  239,  241,
      243,  245,  247,  257,  267,  249,  255,  267,  267,  251,
      237,  267,  267,  235,  253,  267,  267,  233,  277,  278,
      240,  242,  244,  246,  248,  258,  250,  256,  267,  252,
      238,  267,  267,  236,  254,  267,  267,  234,  283,    1,
       12,    0,    4,  262,  263,  261,  282,  264,    0,    0,
      260,  260,  260,  260,  268,  268,    0,  269,  265,  266,
        0,  285,   19,   13,   15,  286,  270,  267,  259,  267,

      199,  267,  265,  267,  267,  266,  201,  267,  267,  267,
      219,  267,   45,   53,  203,  213,  267,   49,   47,   51,
      215,  267,  267,  267,  217,   14,   16,  267,  205,    7,
      229,  231,  209,  211,  195,  197,  191,   21,   20,  223,
       11,  267,  221,  193,  267,  267,  227,  225,  267,  267,
      187,  189,  267,  267,  267,  267,  267,  207,  267,  267,
      267,  267,  200,  267,  267,  202,  267,  267,  267,  220,
      267,   46,   54,  204,  214,  267,   50,   48,   52,  216,
      267,  267,  218,  267,  206,  230,  232,  210,  212,  196,
      198,  192,  224,  267,  267,  222,  194,  267,  267,  228,

      226,  267,  267,  188,  190,  267,  267,  267,  267,  267,
      208,  267,  267,  267,  284,    0,    3,    3,  262,    0,
        2,    2,  260,  260,   23,   27,  260,   26,   24,   25,
      260,  271,  159,  161,  185,  267,  157,  163,  267,  165,
      143,  145,  151,  153,   97,  267,  267,   99,  101,  267,
      169,  267,  267,  267,  173,  175,  177,  107,  109,  103,
      105,  149,  147,  179,  181,  267,  267,  155,  141,  267,
      183,  167,  135,  137,  139,  131,  133,  129,  127,  125,
      123,  121,  117,  119,  115,  113,  111,  171,  160,  162,
      186,  267,  158,  164,  267,  166,  144,  146,  152,  154,

       98,  267,  267,  100,  102,  170,  267,  174,  176,  178,
      108,  110,  104,  106,  150,  148,  180,  182,  267,  267,
      156,  142,  267,  184,  168,  136,  138,  140,  132,  134,
      130,  128,  126,  124,  122,  118,  120,  116,  114,  112,
      172,    4,  262,    5,  260,  260,   22,  267,   63,   75,
       77,   35,   43,  267,   39,   37,   41,   61,  267,  267,
       81,  267,  267,  267,  267,   73,   79,   83,   85,   65,
       67,   71,   69,   87,   89,   91,   93,   95,  267,   64,
       76,   78,   36,   44,  267,   40,   38,   42,   62,   82,
       74,   80,   84,   86,   66,   68,   72,   70,   88,   90,

       92,   94,   96,  262,    6,   29,   30,   28,   31,   32,
       59,  267,   10,   55,    8,  267,  267,  267,   60,  267,
      267,    9,   57,  267,  267,   33,   56,   34,  267,  267,
       58,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,    1,   23,
       24,   25,    1,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   37,   48,   49,   50,   51,
       52,    1,   53,    1,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   37,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   37,   75,   76,
       77,   78,    1,   79,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[80] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    4,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1
    } ;

static const flex_int16_t yy_base[440] =
    {   0,
        0,    0,  986,  987,  983,  987,  960,  978,   61,   75,
       64,   89,  972,  987,  987,  987,  987,  987,  987,   69,
      987,  103,  119,  139,   62,  957,   87,   94,  183,  227,
      145,  161,  187,  107,  130,  155,  202,  141,  958,  198,
      957,  241,  221,  238,  242,  262,  103,  956,  987,  987,
      216,  121,  244,  256,  266,  955,  153,  231,   93,  177,
      954,  273,  253,  280,  281,  299,  164,  953,  895,  971,
      987,  967,  966,  355,  369,  107,  987,  383,  960,  959,
        0,  918,  332,  924,  397,  413,  433,  449,  987,  987,
      469,  987,  987,  987,  987,  987,  109,  190,  987,  288,

      315,  944,  943,  119,  313,  942,  204,  204,  343,  473,
      400,  330,  242,  281,  474,  941,  327,  940,  939,  938,
      937,  315,  344,  325,  312,  936,  935,  357,  934,  426,
      933,  485,  371,  385,  932,  931,  452,  930,  929,  928,
      123,  415,  927,  926,  482,  427,  925,  429,  471,  488,
      496,  500,  491,  417,  462,  497,  509,  924,  513,  463,
      414,  499,  185,  135,  428,  923,  399,  172,  502,  506,
      283,  922,  921,  510,  920,  516,  919,  918,  917,  916,
      517,  470,   79,  519,  915,  914,  523,  520,  526,  913,
      912,  531,  911,  532,  386,  910,  909,  537,  524,  908,

      527,  530,  533,  546,  552,  538,  541,  539,  543,  557,
      907,  565,  536,  544,  987,  923,  987,  987,  604,  917,
      987,  987,    0,  880,    0,    0,  893,    0,    0,    0,
      877,  618,  543,  579,  987,  595,  901,  900,  591,  592,
      596,  597,  899,  622,  623,  625,  604,  555,  898,  620,
      897,  621,  634,  641,  640,  622,  637,  896,  895,  894,
      893,  647,  650,  892,  891,  652,  653,  654,  890,  372,
      889,  655,  888,  658,  887,  886,  660,  885,  884,  883,
      882,  881,  880,  879,  878,  877,  876,  875,  874,  873,
      987,  657,  872,  871,  661,  870,  664,  666,  869,  868,

      867,  676,  218,  866,  865,  864,  670,  863,  678,  679,
      862,  861,  860,  859,  681,  682,  858,  857,  683,  684,
      671,  856,  685,  855,  677,  854,  686,  853,  852,  690,
      851,  850,  849,  848,  847,  846,  845,  844,  843,  842,
      841,  987,  737,  987,  831,  683,    0,  680,  839,  838,
      837,  680,  681,  737,  836,  835,  834,  833,  692,  716,
      832,  695,  699,  701,  724,  831,  830,  829,  828,  827,
      826,  825,  824,  823,  822,  821,  820,  818,  703,  813,
      808,  800,  795,  792,  739,  791,  789,  788,  787,  786,
      785,  783,  781,  780,  779,  778,  777,  776,  775,  774,

      773,  771,  770,  987,    0,    0,    0,    0,    0,    0,
      768,  741,  767,  766,  697,  751,  740,  752,  554,  753,
      754,  551,  528,  756,  757,  398,  763,  370,  759,  764,
      272,  987,  815,  820,   82,  823,  828,  833,  836
    } ;

static const flex_int16_t yy_def[440] =
    {   0,
      432,    1,  432,  432,  432,  432,  432,  433,  432,  432,
      432,  432,  434,  432,  432,  432,  432,  432,  432,  435,
      432,  432,  432,  432,  432,  432,  432,  432,  436,  436,
       30,   30,   30,   30,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  432,  432,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  432,  432,
      432,  437,  432,  432,  432,  432,  432,  432,  438,  432,
      439,  439,  439,  439,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,   30,  432,   30,

       30,  436,  436,  436,  436,  436,   30,  436,   30,   30,
      436,   30,   30,   30,   30,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  432,  437,  432,  432,  432,  438,
      432,  432,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  432,   30,   30,  432,  436,  436,  436,  436,   30,
      436,  436,  436,   30,   30,   30,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      432,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  432,  432,  432,  439,  439,  439,  436,  436,  436,
      436,   30,   30,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  432,  439,  439,  439,  439,  439,  439,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,    0,  432,  432,  432,  432,  432,  432,  432
    } ;

static const flex_int16_t yy_nxt[1067] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,    4,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   39,   45,   46,   39,   39,   39,   47,   39,
       48,   49,   50,    4,   51,   52,   53,   54,   55,   56,
       39,   57,   58,   59,   60,   61,   62,   63,   64,   39,
       65,   66,   39,   39,   39,   67,   39,   68,   69,   74,
       74,   74,   76,   76,   92,   93,   81,   74,   74,   74,
       74,   74,   74,   75,   75,   75,   82,   77,   83,   84,

       99,   75,   75,   75,   75,   75,   75,   78,   78,   78,
       95,   96,   97,   97,   99,   78,   78,   78,   78,   78,
       78,   85,   85,   86,   99,   76,   76,   97,   97,   87,
       88,   87,   87,   87,   87,   98,   89,   85,   85,   86,
       99,  102,   99,  161,   99,   87,   88,   87,   87,   87,
       87,   99,   89,  236,  306,  264,   99,   86,   86,   86,
      126,  190,   99,  191,   90,   87,   87,   87,   87,   87,
       87,  109,   89,  110,   99,  127,   99,  166,   91,  102,
       90,  128,  135,  167,  136,   99,  111,  112,  113,   98,
      114,  115,  129,   99,  291,  116,  117,  292,   99,  118,

       90,   98,   98,   98,   99,  119,   99,  184,  120,   98,
       98,   98,  100,   98,  101,   98,  103,  185,   98,   99,
      104,  121,  105,   99,  102,   99,  122,  137,  138,  123,
      124,  214,   98,  130,  192,  125,  295,   99,  102,   99,
      131,  132,   99,  139,  106,   98,   98,   98,   99,  238,
      133,  134,   99,   98,   98,  107,   98,   98,   98,   99,
      103,  108,   99,   99,  144,   99,  145,  146,  147,  140,
       98,  141,  150,  162,   99,  163,  102,   99,  148,  151,
      164,  142,  165,   99,  149,  152,  153,   99,  106,  154,
      155,  143,  156,   99,   99,  389,  186,  187,  168,  157,

      169,   99,   99,  158,   99,  159,  188,  189,  160,   98,
      171,  172,  170,  173,  174,  102,  233,  234,  175,  176,
       99,  177,  102,  197,  235,  198,  199,  178,  180,  193,
      179,  194,  181,   99,   99,  182,   99,  300,  200,  203,
      195,  183,  237,   98,  248,  204,   99,  201,   99,  102,
      196,  205,  206,  202,  207,  208,  244,  209,   98,  225,
      251,  226,  227,  210,  102,   99,  247,  211,  250,  212,
      228,   98,  213,  219,  219,  219,  229,  102,   99,  230,
      239,  219,  219,  219,  219,  219,  219,   75,   75,   75,
      249,   99,   99,   99,  252,   75,   75,   75,   75,   75,

       75,   78,   78,   78,  258,  374,   99,   99,  259,   78,
       78,   78,   78,   78,   78,   85,   85,   86,  260,   99,
       99,   99,  261,   87,   88,   87,   87,   87,   87,  241,
       89,   86,   86,   86,  242,   99,   99,  243,   99,   87,
       87,   87,   87,   87,   87,  280,   89,   99,   99,   99,
       99,   87,   87,   87,  318,  253,  265,  288,   90,   87,
       87,   87,   87,   87,   87,  254,   89,   87,   87,   87,
      269,  294,  268,   99,   90,   87,   87,   87,   87,   87,
       87,  262,   89,   99,   99,  293,  263,  232,  232,  232,
      287,   99,   99,  281,   90,  232,  232,  232,  232,  232,

      232,   98,  245,   99,  240,  246,   99,  102,  102,   99,
       90,  266,   99,  255,  256,  270,  267,   99,   99,  257,
       99,   99,  273,   99,  274,  275,  276,   99,  277,  278,
       99,   99,  271,  272,   99,  283,  279,   99,   99,  285,
       99,   99,  282,  305,   99,   99,  284,   99,   99,   99,
      286,   99,   99,   99,   99,  289,  290,   99,   99,   99,
       99,  296,   99,  297,   99,   99,  301,   99,  298,  302,
      299,   98,   99,   99,  304,   99,   99,  102,   99,  308,
      309,  311,  303,  307,  312,  310,   99,  313,  315,  359,
      314,  340,  317,  316,  319,  322,  321,  333,  334,  320,

      326,  323,  327,  328,  324,  325,  329,   98,  330,  331,
      332,  336,   99,  102,  341,  335,   99,   99,   99,  338,
       98,  337,  343,  343,  343,   99,  102,  348,  349,  339,
      343,  343,  343,  343,  343,  343,  232,  232,  232,  350,
      351,   99,   99,   99,  232,  232,  232,  232,  232,  232,
       98,   98,  352,  353,  358,   99,  102,  102,   99,  354,
      360,   99,   99,  355,  362,  366,  361,  364,   99,  356,
      363,   99,  357,   99,   99,   99,   99,  365,   99,   99,
      367,   99,   99,  372,  377,   99,  378,   99,  373,  375,
      368,   99,   99,  369,  376,  370,  371,   99,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   98,   98,
      406,   99,  407,   99,  102,  102,   99,  379,   99,  411,
       99,  408,   99,  413,   99,  380,  415,  409,  397,  416,
      410,  383,  384,  398,  381,  417,  382,   99,  385,  400,
      402,  386,  390,  401,  403,   99,  399,  387,  391,  392,
      388,  393,  394,  395,  396,  404,  404,  404,   99,  414,
       99,   99,   99,  404,  404,  404,  404,  404,  404,  419,
      418,  421,   99,   99,   99,   99,  412,   99,   99,  423,
       99,  424,  422,  426,   99,   99,  427,   99,   99,   99,
      429,   99,   99,  430,   99,   99,   99,   99,   99,   99,

       99,   99,   99,  431,   99,  420,   99,   99,   99,   99,
       99,  425,   99,   99,  428,   72,   99,   72,   72,   72,
       79,   99,   79,   79,   79,  102,  102,  102,  216,   99,
      216,  216,  216,  220,   99,  220,  220,  220,  223,   99,
      223,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,  405,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,  347,  346,  345,  344,  342,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,  231,  224,  222,  221,
      218,  217,   70,  215,   99,   99,   99,   99,   99,   99,
       94,   80,   73,   71,   70,  432,    3,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,

      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432
    } ;

static const flex_int16_t yy_chk[1067] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
        9,    9,   11,   11,   25,   25,  435,    9,    9,    9,
        9,    9,    9,   10,   10,   10,   20,   12,   20,   20,

      183,   10,   10,   10,   10,   10,   10,   12,   12,   12,
       27,   27,   28,   28,   59,   12,   12,   12,   12,   12,
       12,   22,   22,   22,   47,   76,   76,   97,   97,   22,
       22,   22,   22,   22,   22,   34,   22,   23,   23,   23,
      104,   34,   52,   47,  141,   23,   23,   23,   23,   23,
       23,   35,   23,  104,  183,  141,  164,   24,   24,   24,
       35,   59,   38,   59,   22,   24,   24,   24,   24,   24,
       24,   31,   24,   31,   57,   35,   36,   52,   22,   31,
       23,   36,   38,   52,   38,   67,   31,   32,   32,   32,
       32,   32,   36,  168,  163,   32,   32,  164,   60,   32,

       24,   29,   29,   29,   29,   32,  163,   57,   32,   29,
       29,   29,   29,   29,   29,   33,   29,   57,   98,   40,
       29,   33,   29,   37,   98,  108,   33,   40,   40,   33,
       33,   67,  107,   37,   60,   33,  168,   51,  107,  303,
       37,   37,   43,   40,   29,   30,   30,   30,   30,  108,
       37,   37,   58,   30,   30,   30,   30,   30,   30,   44,
       30,   30,   42,   45,   43,   53,   43,   43,   44,   42,
      113,   42,   45,   51,   63,   51,  113,   54,   44,   45,
       51,   42,   51,   46,   44,   45,   45,   55,   30,   46,
       46,   42,   46,  431,   62,  303,   58,   58,   53,   46,

       53,   64,   65,   46,  171,   46,   58,   58,   46,  114,
       54,   54,   53,   54,   54,  114,  100,  100,   54,   54,
       66,   54,  100,   63,  101,   63,   63,   54,   55,   62,
       54,   62,   55,  125,  105,   55,  122,  171,   64,   65,
       62,   55,  105,  101,  122,   65,  124,   64,  117,  101,
       62,   65,   65,   64,   66,   66,  112,   66,  112,   83,
      125,   83,   83,   66,  112,  123,  117,   66,  124,   66,
       83,  109,   66,   74,   74,   74,   83,  109,  128,   83,
      109,   74,   74,   74,   74,   74,   74,   75,   75,   75,
      123,  428,  133,  270,  128,   75,   75,   75,   75,   75,

       75,   78,   78,   78,  133,  270,  134,  195,  133,   78,
       78,   78,   78,   78,   78,   85,   85,   85,  134,  426,
      167,  111,  134,   85,   85,   85,   85,   85,   85,  111,
       85,   86,   86,   86,  111,  161,  142,  111,  154,   86,
       86,   86,   86,   86,   86,  154,   86,  130,  146,  165,
      148,   87,   87,   87,  195,  130,  142,  161,   85,   87,
       87,   87,   87,   87,   87,  130,   87,   88,   88,   88,
      148,  167,  146,  137,   86,   88,   88,   88,   88,   88,
       88,  137,   88,  155,  160,  165,  137,   91,   91,   91,
      160,  182,  149,  155,   87,   91,   91,   91,   91,   91,

       91,  110,  115,  145,  110,  115,  132,  110,  115,  150,
       88,  145,  153,  132,  132,  149,  145,  151,  156,  132,
      162,  152,  151,  169,  151,  151,  152,  170,  152,  152,
      157,  174,  150,  150,  159,  157,  153,  176,  181,  159,
      184,  188,  156,  182,  187,  199,  157,  189,  201,  423,
      159,  202,  192,  194,  203,  162,  162,  213,  198,  206,
      208,  169,  207,  170,  209,  214,  174,  204,  170,  174,
      170,  233,  422,  205,  181,  419,  248,  233,  210,  187,
      187,  188,  176,  184,  188,  187,  212,  189,  192,  248,
      189,  213,  194,  192,  198,  201,  199,  207,  208,  198,

      204,  202,  204,  204,  203,  203,  205,  234,  205,  205,
      206,  210,  239,  234,  214,  209,  236,  241,  242,  212,
      240,  210,  219,  219,  219,  247,  240,  236,  239,  212,
      219,  219,  219,  219,  219,  219,  232,  232,  232,  241,
      242,  250,  252,  256,  232,  232,  232,  232,  232,  232,
      244,  245,  246,  246,  247,  253,  244,  245,  257,  246,
      250,  255,  254,  246,  253,  256,  252,  255,  262,  246,
      254,  263,  246,  266,  267,  268,  272,  255,  292,  274,
      257,  277,  295,  268,  274,  297,  277,  298,  268,  272,
      262,  307,  321,  263,  272,  266,  267,  302,  325,  309,

      310,  348,  315,  316,  319,  320,  323,  327,  352,  353,
      346,  330,  346,  359,  352,  353,  362,  292,  415,  348,
      363,  346,  364,  359,  379,  295,  362,  346,  321,  363,
      346,  302,  302,  321,  297,  364,  298,  360,  302,  325,
      327,  302,  307,  325,  330,  365,  323,  302,  309,  310,
      302,  315,  316,  319,  320,  343,  343,  343,  354,  360,
      385,  417,  412,  343,  343,  343,  343,  343,  343,  379,
      365,  412,  416,  418,  420,  421,  354,  424,  425,  417,
      429,  418,  416,  421,  427,  430,  424,  414,  413,  411,
      427,  403,  402,  429,  401,  400,  399,  398,  397,  396,

      395,  394,  393,  430,  392,  385,  391,  390,  389,  388,
      387,  420,  386,  384,  425,  433,  383,  433,  433,  433,
      434,  382,  434,  434,  434,  436,  436,  436,  437,  381,
      437,  437,  437,  438,  380,  438,  438,  438,  439,  378,
      439,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  361,  358,  357,  356,  355,  351,  350,
      349,  345,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  329,  328,  326,  324,  322,  318,  317,
      314,  313,  312,  311,  308,  306,  305,  304,  301,  300,
      299,  296,  294,  293,  290,  289,  288,  287,  286,  285,

      284,  283,  282,  281,  280,  279,  278,  276,  275,  273,
      271,  269,  265,  264,  261,  260,  259,  258,  251,  249,
      243,  238,  237,  231,  227,  224,  220,  216,  211,  200,
      197,  196,  193,  191,  190,  186,  185,  180,  179,  178,
      177,  175,  173,  172,  166,  158,  147,  144,  143,  140,
      139,  138,  136,  135,  131,  129,  127,  126,  121,  120,
      119,  118,  116,  106,  103,  102,   84,   82,   80,   79,
       73,   72,   70,   69,   68,   61,   56,   48,   41,   39,
       26,   13,    8,    7,    5,    3,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,

      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  432,  432,  432,  432
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"

#include <stdio.h>
#include <string.h>


#include "grammar.h"


/* Externally defined functions used here */
extern void fatalError(const char *str);


/* Declarations of locally defined functions */
void reset_lexer();
int from_binary(const char * s);


/*****************************/
/* Locally defined functions */
void reset_lexer() { YY_FLUSH_BUFFER;  yylineno = 1; }

int from_binary(const char * s) {
 char aux[60];
 
  if (strlen(s) > 59) { fatalError("Binary is too long"); }  
  strncpy(aux,s,strlen(s)); aux[strlen(s)] = 0x0;
  if (aux[strlen(aux)-1] == 'B' || aux[strlen(aux)-1] == 'b') {
     aux[strlen(aux)-1] = 0x0;
  }
  return (int) strtol(aux, NULL, 2);

}

int from_hexa(const char * s) {
 char aux[60];

  if (strlen(s) > 59) { fatalError("Hexadecimal number is too long"); }   
  strncpy(aux,s,strlen(s)); aux[strlen(s)] = 0x0;
  if (aux[strlen(aux)-1] == 'H' || aux[strlen(aux)-1] == 'h') {
     aux[strlen(aux)-1] = 0x0;
  }
  return (int) strtol(aux, NULL, 16);

}


#line 867 "lex.c"
#define YY_NO_INPUT 1
#line 869 "lex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 53 "lex.l"

#line 1086 "lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 433 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 987 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "lex.l"
/* eat up whitespace */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 55 "lex.l"
{ yylval.normal = yytext[1]; return CHAR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "lex.l"
{ yylval.normal = yytext[1]; return CHAR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "lex.l"
{  strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-2]=0x0;return STRING; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "lex.l"
{  strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-2]=0x0;return STRING; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "lex.l"
{ return DEFB; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "lex.l"
{ return IF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "lex.l"
{ return IFDEF; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "lex.l"
{ return IFNDEF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "lex.l"
{ return ENDIF; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "lex.l"
{ return NEQUAL;  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "lex.l"
{ return NEQUAL;  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "lex.l"
{ return EQUAL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "lex.l"
{ return GREATEREQ; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "lex.l"
{ return GREATEREQ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "lex.l"
{ return GREATERTHAN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "lex.l"
{ return GREATERTHAN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "lex.l"
{ return LESSTHAN;    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "lex.l"
{ return LESSEQ; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "lex.l"
{ return LESSTHAN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "lex.l"
{ return LESSEQ; } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "lex.l"
{ return EQU;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "lex.l"
{ return DEFB; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "lex.l"
{ return DEFS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "lex.l"
{ return DEFW; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "lex.l"
{ return DEFB; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "lex.l"
{ return DEFD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "lex.l"
{ return DEFB; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "lex.l"
{ return DEFB; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "lex.l"
{ return DEFD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "lex.l"
{ return DEFS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "lex.l"
{ return DEFW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "lex.l"
{ return DEFINED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "lex.l"
{ return DEFINED; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "lex.l"
{ return DEFB; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lex.l"
{ return DEFB; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "lex.l"
{ return DEFS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "lex.l"
{ return DEFS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "lex.l"
{ return DEFB; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "lex.l"
{ return DEFB; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "lex.l"
{ return DEFW; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "lex.l"
{ return DEFW; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "lex.l"
{ return DEFC; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 97 "lex.l"
{ return DEFC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 98 "lex.l"
{ return DEFB; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "lex.l"
{ return DEFB; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "lex.l"
{ return DEFS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "lex.l"
{ return DEFS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "lex.l"
{ return DEFB; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "lex.l"
{ return DEFB; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "lex.l"
{ return DEFW; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "lex.l"
{ return DEFW; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "lex.l"
{ return DEFD; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "lex.l"
{ return DEFD; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "lex.l"
{ return ERROR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "lex.l"
{ return INCLUDE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "lex.l"
{ return INCLUDEBIN;  }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "lex.l"
{ return INCLUDEBIN;  }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "lex.l"
{ return ALIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "lex.l"
{ return ALIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "lex.l"
{ return DJNZ; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "lex.l"
{ return DJNZ; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "lex.l"
{ return CALL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "lex.l"
{ return CALL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "lex.l"
{ return OTDR; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "lex.l"
{ return OTDR; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 120 "lex.l"
{ return OTIR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "lex.l"
{ return OTIR; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 122 "lex.l"
{ return OUTI; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 123 "lex.l"
{ return OUTI; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "lex.l"
{ return OUTD; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "lex.l"
{ return OUTD; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "lex.l"
{ return INDR; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 127 "lex.l"
{ return INDR; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "lex.l"
{ return CPDR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "lex.l"
{ return CPDR; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "lex.l"
{ return CPIR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "lex.l"
{ return CPIR; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "lex.l"
{ return INIR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "lex.l"
{ return INIR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "lex.l"
{ return HALT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "lex.l"
{ return HALT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "lex.l"
{ return LDDR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "lex.l"
{ return LDDR; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "lex.l"
{ return LDIR; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "lex.l"
{ return LDIR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "lex.l"
{ return PUSH; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "lex.l"
{ return PUSH; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "lex.l"
{ return RETI; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "lex.l"
{ return RETI; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "lex.l"
{ return RETN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "lex.l"
{ return RETN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "lex.l"
{ return RLCA; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "lex.l"
{ return RLCA; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "lex.l"
{ return RRCA; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "lex.l"
{ return RRCA; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "lex.l"
{ return DEC; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "lex.l"
{ return DEC; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "lex.l"
{ return END; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "lex.l"
{ return END; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "lex.l"
{ return EQU; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "lex.l"
{ return EQU; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 156 "lex.l"
{ return IYH; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "lex.l"
{ return IYH; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "lex.l"
{ return IYL; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "lex.l"
{ return IYL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "lex.l"
{ return IXH; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 161 "lex.l"
{ return IXH; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 162 "lex.l"
{ return IXL; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 163 "lex.l"
{ return IXL; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 164 "lex.l"
{ return SUB; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 165 "lex.l"
{ return SUB; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 166 "lex.l"
{ return SRL; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 167 "lex.l"
{ return SRL; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 168 "lex.l"
{ return SRA; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 169 "lex.l"
{ return SRA; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 170 "lex.l"
{ return SLA; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 171 "lex.l"
{ return SLA; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 172 "lex.l"
{ return SLL; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 173 "lex.l"
{ return SLL; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 174 "lex.l"
{ return SET; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 175 "lex.l"
{ return SET; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 176 "lex.l"
{ return SCF; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 177 "lex.l"
{ return SCF; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 178 "lex.l"
{ return SBC; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 179 "lex.l"
{ return SBC; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 180 "lex.l"
{ return RST; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 181 "lex.l"
{ return RST; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 182 "lex.l"
{ return RRD; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 183 "lex.l"
{ return RRD; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 184 "lex.l"
{ return RRA; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 185 "lex.l"
{ return RRA; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 186 "lex.l"
{ return RRC; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 187 "lex.l"
{ return RRC; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 188 "lex.l"
{ return RLA; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 189 "lex.l"
{ return RLA; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 190 "lex.l"
{ return RLC; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 191 "lex.l"
{ return RLC; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 192 "lex.l"
{ return RLD; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 193 "lex.l"
{ return RLD; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 194 "lex.l"
{ return POP; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 195 "lex.l"
{ return POP; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 196 "lex.l"
{ return CPD; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 197 "lex.l"
{ return CPD; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 198 "lex.l"
{ return CPI; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 199 "lex.l"
{ return CPI; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 200 "lex.l"
{ return LDI; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 201 "lex.l"
{ return LDI; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 202 "lex.l"
{ return LDD; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 203 "lex.l"
{ return LDD; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 204 "lex.l"
{ return CPL; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 205 "lex.l"
{ return CPL; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 206 "lex.l"
{ return DAA; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 207 "lex.l"
{ return DAA; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 208 "lex.l"
{ return OUT; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 209 "lex.l"
{ return OUT; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 210 "lex.l"
{ return AND; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 211 "lex.l"
{ return AND; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 212 "lex.l"
{ return ADC; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 213 "lex.l"
{ return ADC; }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 214 "lex.l"
{ return ADD; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 215 "lex.l"
{ return ADD; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 216 "lex.l"
{ return BIT; }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 217 "lex.l"
{ return BIT; }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 218 "lex.l"
{ return CCF; }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 219 "lex.l"
{ return CCF; }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 220 "lex.l"
{ return RET; }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 221 "lex.l"
{ return RET; }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 222 "lex.l"
{ return EXX; }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 223 "lex.l"
{ return EXX; }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 224 "lex.l"
{ return XOR; }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 225 "lex.l"
{ return XOR; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 226 "lex.l"
{ return INC; }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 227 "lex.l"
{ return INC; }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 228 "lex.l"
{ return IND; }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 229 "lex.l"
{ return IND; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 230 "lex.l"
{ return INI; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 231 "lex.l"
{ return INI; }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 232 "lex.l"
{ return NEG; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 233 "lex.l"
{ return NEG; }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 234 "lex.l"
{ return NOP; }
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 235 "lex.l"
{ return NOP; }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 236 "lex.l"
{ return RES; }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 237 "lex.l"
{ return RES; }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 238 "lex.l"
{ return AFPLUS; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 239 "lex.l"
{ return AFPLUS; }
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 240 "lex.l"
{ return RL; }
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 241 "lex.l"
{ return RL; }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 242 "lex.l"
{ return RR; }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 243 "lex.l"
{ return RR; }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 244 "lex.l"
{ return LD; }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 245 "lex.l"
{ return LD; }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 246 "lex.l"
{ return OR; }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 247 "lex.l"
{ return OR; }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 248 "lex.l"
{ return JP; }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 249 "lex.l"
{ return JP; }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 250 "lex.l"
{ return JR; }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 251 "lex.l"
{ return JR; }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 252 "lex.l"
{ return AF; }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 253 "lex.l"
{ return AF; }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 254 "lex.l"
{ return BC; }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 255 "lex.l"
{ return BC; }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 256 "lex.l"
{ return DE; }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 257 "lex.l"
{ return DE; }
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 258 "lex.l"
{ return HL; }
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 259 "lex.l"
{ return HL; }
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 260 "lex.l"
{ return SP; }
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 261 "lex.l"
{ return SP; }
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 262 "lex.l"
{ return IX; }
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 263 "lex.l"
{ return IX; }
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 264 "lex.l"
{ return IY; }
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 265 "lex.l"
{ return IY; }
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 266 "lex.l"
{ return DI; }
	YY_BREAK
case 214:
YY_RULE_SETUP
#line 267 "lex.l"
{ return DI; }
	YY_BREAK
case 215:
YY_RULE_SETUP
#line 268 "lex.l"
{ return EI; }
	YY_BREAK
case 216:
YY_RULE_SETUP
#line 269 "lex.l"
{ return EI; }
	YY_BREAK
case 217:
YY_RULE_SETUP
#line 270 "lex.l"
{ return EX; }
	YY_BREAK
case 218:
YY_RULE_SETUP
#line 271 "lex.l"
{ return EX; }
	YY_BREAK
case 219:
YY_RULE_SETUP
#line 272 "lex.l"
{ return CP; }
	YY_BREAK
case 220:
YY_RULE_SETUP
#line 273 "lex.l"
{ return CP; }
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 274 "lex.l"
{ return NZ; }
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 275 "lex.l"
{ return NZ; }
	YY_BREAK
case 223:
YY_RULE_SETUP
#line 276 "lex.l"
{ return NC; }
	YY_BREAK
case 224:
YY_RULE_SETUP
#line 277 "lex.l"
{ return NC; }
	YY_BREAK
case 225:
YY_RULE_SETUP
#line 278 "lex.l"
{ return PO; }
	YY_BREAK
case 226:
YY_RULE_SETUP
#line 279 "lex.l"
{ return PO; }
	YY_BREAK
case 227:
YY_RULE_SETUP
#line 280 "lex.l"
{ return PE; }
	YY_BREAK
case 228:
YY_RULE_SETUP
#line 281 "lex.l"
{ return PE; }
	YY_BREAK
case 229:
YY_RULE_SETUP
#line 282 "lex.l"
{ return IM; }
	YY_BREAK
case 230:
YY_RULE_SETUP
#line 283 "lex.l"
{ return IM; }
	YY_BREAK
case 231:
YY_RULE_SETUP
#line 284 "lex.l"
{ return IN; }
	YY_BREAK
case 232:
YY_RULE_SETUP
#line 285 "lex.l"
{ return IN; }
	YY_BREAK
case 233:
YY_RULE_SETUP
#line 286 "lex.l"
{ return Z; }
	YY_BREAK
case 234:
YY_RULE_SETUP
#line 287 "lex.l"
{ return Z; }
	YY_BREAK
case 235:
YY_RULE_SETUP
#line 288 "lex.l"
{ return P; }
	YY_BREAK
case 236:
YY_RULE_SETUP
#line 289 "lex.l"
{ return P; }
	YY_BREAK
case 237:
YY_RULE_SETUP
#line 290 "lex.l"
{ return M; }
	YY_BREAK
case 238:
YY_RULE_SETUP
#line 291 "lex.l"
{ return M; }
	YY_BREAK
case 239:
YY_RULE_SETUP
#line 292 "lex.l"
{ return A; }
	YY_BREAK
case 240:
YY_RULE_SETUP
#line 293 "lex.l"
{ return A; }
	YY_BREAK
case 241:
YY_RULE_SETUP
#line 294 "lex.l"
{ return B; }
	YY_BREAK
case 242:
YY_RULE_SETUP
#line 295 "lex.l"
{ return B; }
	YY_BREAK
case 243:
YY_RULE_SETUP
#line 296 "lex.l"
{ return C; }
	YY_BREAK
case 244:
YY_RULE_SETUP
#line 297 "lex.l"
{ return C; }
	YY_BREAK
case 245:
YY_RULE_SETUP
#line 298 "lex.l"
{ return D; }
	YY_BREAK
case 246:
YY_RULE_SETUP
#line 299 "lex.l"
{ return D; }
	YY_BREAK
case 247:
YY_RULE_SETUP
#line 300 "lex.l"
{ return E; }
	YY_BREAK
case 248:
YY_RULE_SETUP
#line 301 "lex.l"
{ return E; }
	YY_BREAK
case 249:
YY_RULE_SETUP
#line 302 "lex.l"
{ return H; }
	YY_BREAK
case 250:
YY_RULE_SETUP
#line 303 "lex.l"
{ return H; }
	YY_BREAK
case 251:
YY_RULE_SETUP
#line 304 "lex.l"
{ return L; }
	YY_BREAK
case 252:
YY_RULE_SETUP
#line 305 "lex.l"
{ return L; }
	YY_BREAK
case 253:
YY_RULE_SETUP
#line 306 "lex.l"
{ return R; }
	YY_BREAK
case 254:
YY_RULE_SETUP
#line 307 "lex.l"
{ return R; }
	YY_BREAK
case 255:
YY_RULE_SETUP
#line 308 "lex.l"
{ return I; }
	YY_BREAK
case 256:
YY_RULE_SETUP
#line 309 "lex.l"
{ return I; }
	YY_BREAK
case 257:
YY_RULE_SETUP
#line 310 "lex.l"
{ return F; }
	YY_BREAK
case 258:
YY_RULE_SETUP
#line 311 "lex.l"
{ return F; }
	YY_BREAK
case 259:
YY_RULE_SETUP
#line 312 "lex.l"
{ strncpy(yylval.literal,yytext,strlen(yytext)); yylval.literal[strlen(yytext)-1]=0x0;return LABEL; }
	YY_BREAK
case 260:
YY_RULE_SETUP
#line 313 "lex.l"
{ strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-1]=0x0;return LABEL; }
	YY_BREAK
case 261:
YY_RULE_SETUP
#line 314 "lex.l"
{ yylval.normal = from_binary(yytext+1); return INTEGER; }
	YY_BREAK
case 262:
YY_RULE_SETUP
#line 315 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 263:
YY_RULE_SETUP
#line 316 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 264:
YY_RULE_SETUP
#line 317 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 265:
YY_RULE_SETUP
#line 318 "lex.l"
{ yylval.normal = from_hexa(yytext); return INTEGER;  }
	YY_BREAK
case 266:
YY_RULE_SETUP
#line 319 "lex.l"
{ yylval.normal = from_hexa(yytext); return INTEGER;  }
	YY_BREAK
case 267:
YY_RULE_SETUP
#line 320 "lex.l"
{ strcpy(yylval.literal,yytext); return LITERAL; }
	YY_BREAK
case 268:
YY_RULE_SETUP
#line 321 "lex.l"
{ yylval.normal = atoi(yytext); return INTEGER; }
	YY_BREAK
case 269:
YY_RULE_SETUP
#line 322 "lex.l"
{ yylval.normal = from_binary(yytext); return INTEGER;  }
	YY_BREAK
case 270:
YY_RULE_SETUP
#line 323 "lex.l"
{ yylval.normal = from_binary(yytext+1); return INTEGER;  }
	YY_BREAK
case 271:
YY_RULE_SETUP
#line 324 "lex.l"
{ yylval.normal = from_hexa(yytext+2); return INTEGER; }
	YY_BREAK
case 272:
/* rule 272 can match eol */
YY_RULE_SETUP
#line 325 "lex.l"
{ return NEWLINE; }
	YY_BREAK
case 273:
YY_RULE_SETUP
#line 326 "lex.l"
{ return MINUS; }
	YY_BREAK
case 274:
YY_RULE_SETUP
#line 327 "lex.l"
{ return COMMA; }
	YY_BREAK
case 275:
YY_RULE_SETUP
#line 328 "lex.l"
{ return PARLEFT; }
	YY_BREAK
case 276:
YY_RULE_SETUP
#line 329 "lex.l"
{ return PARRIGHT; }
	YY_BREAK
case 277:
YY_RULE_SETUP
#line 330 "lex.l"
{ return PARLEFT; }
	YY_BREAK
case 278:
YY_RULE_SETUP
#line 331 "lex.l"
{ return PARRIGHT; }
	YY_BREAK
case 279:
YY_RULE_SETUP
#line 332 "lex.l"
{ return PLUS; }
	YY_BREAK
case 280:
YY_RULE_SETUP
#line 333 "lex.l"
{ return MULT; }
	YY_BREAK
case 281:
YY_RULE_SETUP
#line 334 "lex.l"
{ return BITAND; }
	YY_BREAK
case 282:
YY_RULE_SETUP
#line 335 "lex.l"
{ return AND; }
	YY_BREAK
case 283:
YY_RULE_SETUP
#line 336 "lex.l"
{ return BITOR;  }
	YY_BREAK
case 284:
YY_RULE_SETUP
#line 337 "lex.l"
{ return OR;  }
	YY_BREAK
case 285:
YY_RULE_SETUP
#line 338 "lex.l"
{ return OPSHLF; }
	YY_BREAK
case 286:
YY_RULE_SETUP
#line 339 "lex.l"
{ return OPSHRT; }
	YY_BREAK
case 287:
YY_RULE_SETUP
#line 340 "lex.l"
{ return DIVIDE; }
	YY_BREAK
case 288:
YY_RULE_SETUP
#line 341 "lex.l"
{ return DOLAR;  }
	YY_BREAK
case 289:
YY_RULE_SETUP
#line 342 "lex.l"
{ return EQUAL;  }
	YY_BREAK
case 290:
YY_RULE_SETUP
#line 343 "lex.l"
{ return EXCLAMATION; }
	YY_BREAK
case 291:
YY_RULE_SETUP
#line 345 "lex.l"
ECHO;
	YY_BREAK
#line 2599 "lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 433 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 433 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 432);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 345 "lex.l"



