
#line 3 "lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 307
#define YY_END_OF_BUFFER 308
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[491] =
    {   0,
        0,    0,  308,  307,    3,  288,  306,  307,  307,  304,
      307,  297,  307,  291,  292,  296,  295,  290,  289,  307,
      303,  284,  284,  284,  307,   25,  305,   24,  307,  255,
      257,  259,  261,  263,  273,  283,  265,  271,  283,  283,
      267,  253,  283,  283,  251,  269,  283,  283,  283,  249,
      293,  294,  256,  258,  260,  262,  264,  274,  266,  272,
      283,  268,  254,  283,  283,  252,  270,  283,  283,  283,
      250,  299,    3,   19,    0,    6,    0,  278,  279,  277,
      298,  280,    0,    0,  276,  276,  276,  276,  276,  276,
      276,  284,  284,    0,  285,  281,  282,    0,    0,    1,

      301,   26,   20,   22,  302,  286,  283,  275,  283,  215,
      283,  281,  283,  283,  283,  282,  217,  283,  283,  283,
      235,  283,   53,   61,  219,  229,  283,   57,   55,   59,
      231,  283,  283,  283,  233,  283,   21,   23,  283,  221,
       14,  245,  247,  225,  227,  211,  213,  207,   28,  283,
       27,  239,   18,  283,  237,  209,  283,  283,  243,  241,
      283,  283,  203,  205,  283,  283,  283,  283,  283,  223,
      283,  283,  283,  283,  283,  216,  283,  283,  283,  218,
      283,  283,  283,  236,  283,   54,   62,  220,  230,  283,
       58,   56,   60,  232,  283,  283,  234,  283,  222,  246,

      248,  226,  228,  212,  214,  208,  283,  240,  283,  283,
      238,  210,  283,  283,  244,  242,  283,  283,  204,  206,
      283,  283,  283,  283,  283,  224,  283,  283,  283,  283,
      300,    0,    5,    5,    0,    0,  278,    0,    4,    4,
      276,  276,   31,   35,  276,   34,   32,   33,  276,  276,
      276,  276,  287,  175,  177,  201,  283,  173,  283,  179,
      283,  181,  159,  161,  167,  169,  111,  283,  283,  113,
      117,  283,  185,  283,  283,  283,  283,  189,  191,  193,
      123,  125,  119,  121,  165,  163,  283,  195,  283,  197,
      115,  283,  283,  171,  157,  283,  199,  183,  151,  153,

      155,  147,  149,  145,  143,  141,  139,  137,  133,  135,
      131,  129,  127,  283,  187,  176,  178,  202,  283,  174,
      283,  180,  283,  182,  160,  162,  168,  170,  112,  283,
      283,  114,  118,  186,  283,  190,  192,  194,  124,  126,
      120,  122,  166,  164,  283,  196,  283,  198,  116,  283,
      283,  172,  158,  283,  200,  184,  152,  154,  156,  148,
      150,  146,  144,  142,  140,  138,  134,  136,  132,  130,
      128,  283,  188,    6,    2,  278,    7,  276,  276,   30,
       29,  276,  276,  283,   75,   77,   89,   91,   43,   51,
      283,   47,   45,   49,   73,  283,  283,  283,   95,  283,

      283,  283,  283,   87,   93,   97,   99,  283,  283,   79,
       81,   85,   83,  101,  103,  105,  107,  109,  283,  283,
       76,   78,   90,   92,   44,   52,  283,   48,   46,   50,
       74,   96,   88,   94,   98,  100,  283,  283,   80,   82,
       86,   84,  102,  104,  106,  108,  110,  283,  278,    8,
       37,   38,   36,   39,   40,  276,  276,   71,  283,   17,
       63,   13,   15,  283,  283,  283,   69,  283,   10,   72,
      283,   70,  283,   11,    9,   12,  283,   16,   65,  283,
       67,  283,   68,   41,   64,   42,  283,  283,   66,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   25,
       26,   27,    1,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   39,   50,   51,   52,   53,
       54,    1,   55,    1,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   66,   39,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   39,   77,   78,
       79,   80,    1,   81,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    4,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    3,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1
    } ;

static yyconst flex_uint16_t yy_base[500] =
    {   0,
        0,    0, 1093, 1094,   80, 1094, 1066, 1085,   79,   73,
       65,  104, 1079, 1094, 1094, 1094, 1094, 1094, 1094,   97,
     1094,  121,  144,  161, 1086,   62, 1062,   63,   71,  206,
      251,  167,  183,  210,   86,   98,  139,  226,   74, 1064,
      186, 1063,  116,  138,  243,  256,  267,  121,   73, 1062,
     1094, 1094,  252,  199,  234,  271,  278, 1061,  187,  283,
      286,  140, 1060,  285,  294,  302,  307,  318,  137,  133,
     1059, 1000,  241, 1094, 1074, 1073, 1074,  366,  381,  150,
     1094,  387, 1066, 1065,    0, 1023,  392, 1029, 1027, 1035,
     1006,  414,  431,  450,  467, 1094, 1094,  486, 1067, 1094,

     1094, 1094, 1094, 1094, 1094,  168,  170, 1094,  303,  327,
     1046, 1045,  194,  227,   99, 1044,  232,  272,  287,  392,
      417,  353,  273,  323,  490, 1043,  125, 1042, 1041, 1040,
     1039,  310,  183,  276,  381,  408, 1038, 1037,   75, 1036,
      443, 1035,  502,  433,  454, 1034, 1033,  500, 1032,  330,
     1031, 1030,  370,  415, 1029,  469,  503,  445, 1028,  383,
      326,  482,  513,  518,  490,  352,  228,  505,  523, 1027,
      525,  479,  520,  528,  451,  544,  499,  533,  369, 1026,
      534,  535,  536,  539,  537, 1025, 1024,  538, 1023,  543,
     1022, 1021, 1020, 1019,  547,  546,  548,  549, 1018, 1017,

      554,  553,  557, 1016, 1015,  550,  555, 1014,  562,  560,
     1013,  565,  569,  558, 1012,  405,  556,  561,  580,  585,
      563,  552,  595,  566,  609, 1011,  620,  623,  572,  418,
     1094, 1027, 1094, 1094, 1029,  587,  629, 1020, 1094, 1094,
        0,  982,    0,    0,  995,    0,    0,    0,  979,  992,
      978,  950,  662,  617,  633, 1094,  630, 1001,  632, 1000,
      629,  637,  559,  633,  999,  641,  649,  667,  648,  564,
      998,  662,  997,  665,  652,  666,  679,  680,  667,  684,
      996,  995,  994,  993,  686,  689,  692,  992,  696,  991,
      990,  693,  695,  699,  989,  698,  988,  700,  987,  715,

      986,  985,  717,  984,  983,  982,  981,  980,  979,  978,
      977,  976,  975,  703,  974,  973,  972, 1094,  701,  971,
      702,  970,  704,  969,  705,  722,  968,  967,  966,  724,
      725,  965,  964,  963,  727,  962,  726,  730,  961,  960,
      959,  958,  731,  733,  728,  957,  729,  956,  955,  734,
      735,  749,  954,  732,  953,  746,  952,  740,  951,  950,
      743,  949,  948,  947,  946,  945,  944,  943,  942,  941,
      940,  745,  939, 1094, 1094,  796, 1094,  928,  729,    0,
        0,  920,  892,  739,  935,  934,  933,  932,  736,  743,
      768,  931,  930,  929,  928,  752,  767,  754,  927,  797,

      799,  796,  798,  926,  925,  924,  923,  737,  801,  922,
      921,  920,  919,  918,  917,  916,  915,  914,  811,  800,
      913,  912,  910,  905,  900,  895,  812,  882,  877,  874,
      873,  872,  871,  870,  869,  867,  761,  765,  866,  865,
      864,  863,  862,  861,  859,  857,  856,  814, 1094,    0,
        0,    0,    0,    0,    0,  845,  816,  851,  817,  850,
      849,  848,  844,  815,  818,  819,  843,  820,  842,  841,
      822,  836,  823,  835,    0,    0,  829,  650,  573,  830,
      489,  831,  435,  343,  832,  300,  833,  834,  242, 1094,
      898,  903,  114,  908,  911,  916,  921,  926,  929

    } ;

static yyconst flex_int16_t yy_def[500] =
    {   0,
      490,    1,  490,  490,  490,  490,  490,  491,  490,  490,
      490,  490,  492,  490,  490,  490,  490,  490,  490,  493,
      490,  490,  490,  490,  494,  490,  490,  490,  490,  495,
      495,   31,   31,   31,   31,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      490,  490,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  490,  490,  490,  496,  490,  497,  490,  490,  490,
      490,  490,  498,  490,  499,  499,  499,  499,  499,  499,
      499,  490,  490,  490,  490,  490,  490,  490,  494,  490,

      490,  490,  490,  490,  490,  490,   31,  490,   31,   31,
      495,  495,  495,  495,  495,  495,   31,  495,   31,   31,
      495,   31,   31,   31,   31,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      490,  496,  490,  490,  497,  497,  490,  498,  490,  490,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  490,   31,   31,  490,  495,  495,  495,  495,
      495,   31,  495,  495,  495,   31,   31,   31,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  490,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  490,  490,  490,  490,  499,  499,  499,
      499,  499,  499,  495,  495,  495,  495,  495,   31,   31,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,

      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  490,  499,
      499,  499,  499,  499,  499,  499,  499,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  499,  499,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  495,  495,    0,
      490,  490,  490,  490,  490,  490,  490,  490,  490

    } ;

static yyconst flex_uint16_t yy_nxt[1176] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,    4,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   40,   46,   47,   48,   40,   40,
       49,   40,   50,   51,   52,    4,   53,   54,   55,   56,
       57,   58,   40,   59,   60,   61,   62,   63,   64,   65,
       66,   40,   67,   68,   69,   40,   40,   70,   40,   71,
       72,   73,   77,   73,   80,   80,  101,  102,  104,  105,
      106,  106,   79,   79,   79,  108,  108,  108,   78,   78,

       78,   79,   79,   79,   79,   79,   79,   78,   78,   78,
       78,   78,   78,   81,  275,  174,  107,  146,   85,  147,
      108,  108,  111,   82,   82,   82,   86,  136,   87,   88,
      137,  259,   82,   82,   82,   82,   82,   82,  108,   89,
       92,   92,   93,  108,   90,  138,  152,  108,  153,   94,
       95,   94,   94,   94,   94,  108,   96,  173,  154,  108,
      108,  108,  108,   92,   92,   93,  269,  139,  155,   80,
       80,   91,   94,   95,   94,   94,   94,   94,  140,   96,
       93,   93,   93,  156,   97,  157,  158,  106,  106,   94,
       94,   94,   94,   94,   94,  119,   96,  120,   98,  206,

      107,  229,  230,  111,  207,  108,  111,   97,  108,  108,
      121,  122,  123,  107,  124,  125,  108,  148,  149,  126,
      127,  108,  150,  128,   97,  107,  107,  107,  108,  129,
      257,  271,  130,  151,  107,  107,  107,  109,  107,  110,
      107,  112,   73,  198,   73,  113,  131,  114,  108,  108,
      108,  132,  115,  199,  133,  134,  108,  180,  258,  141,
      135,  307,  107,  181,  108,  108,  142,  143,  111,  116,
      107,  107,  107,  108,  108,  159,  144,  145,  108,  107,
      107,  117,  107,  107,  107,  160,  112,  118,  162,  108,
      182,  161,  183,  108,  108,  163,  166,  167,  108,  168,

      108,  164,  165,  107,  184,  108,  169,  108,  108,  111,
      170,  175,  171,  176,  116,  172,  108,  107,  177,  260,
      178,  272,  108,  111,  108,  179,  261,  185,  186,  108,
      187,  188,  108,  254,  255,  189,  190,  256,  191,  111,
      108,  270,  194,  208,  192,  209,  195,  193,  108,  196,
      200,  201,  108,  107,  210,  197,  204,  107,  205,  111,
      202,  203,  215,  111,  211,  108,  212,  218,  213,  214,
      287,  216,  296,  219,  108,  222,  223,  217,  224,  220,
      221,  266,  306,  107,  225,  237,  237,  237,  226,  111,
      227,  108,  108,  228,  237,  237,  237,  237,  237,  237,

       79,   79,   79,  108,  288,  108,   82,   82,   82,   79,
       79,   79,   79,   79,   79,   82,   82,   82,   82,   82,
       82,  243,  107,  244,  245,  262,  295,  108,  111,  321,
      108,  273,  246,   92,   92,   93,  274,  108,  247,  108,
      108,  248,   94,   95,   94,   94,   94,   94,  263,   96,
       93,   93,   93,  264,  289,  108,  265,  108,  290,   94,
       94,   94,   94,   94,   94,  108,   96,  108,  281,   94,
       94,   94,  282,  108,  276,  353,  108,   97,   94,   94,
       94,   94,   94,   94,  277,   96,   94,   94,   94,  283,
      373,  108,  294,  284,   97,   94,   94,   94,   94,   94,

       94,  108,   96,  291,  108,  253,  253,  253,  313,  316,
      317,  108,  108,   97,  253,  253,  253,  253,  253,  253,
      267,  108,  108,  268,  108,  108,  111,  108,  297,  298,
       97,  285,  278,  279,  292,  108,  286,  305,  280,  293,
      108,  299,  108,  300,  301,  108,  302,  108,  303,  304,
      108,  309,  308,  311,  318,  108,  108,  108,  108,  108,
      108,  108,  310,  319,  312,  108,  108,  314,  108,  108,
      108,  108,  108,  315,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  375,
      236,  108,  320,  328,  108,  108,  329,  324,  325,  330,

      396,  323,  108,  326,  387,  327,  332,  108,  322,  343,
      364,  331,  336,  337,  344,  335,  339,  108,  338,  340,
      341,  333,  345,  342,  346,  334,  347,  349,  350,  354,
      348,  108,  352,  351,  355,  356,  357,  363,  358,  359,
      366,  360,  108,  361,  362,  108,  372,  107,  376,  376,
      376,  108,  108,  111,  108,  108,  365,  376,  376,  376,
      376,  376,  376,  107,  384,  367,  385,  107,  386,  111,
      108,  107,  108,  111,  108,  368,  369,  111,  388,  107,
      371,  253,  253,  253,  108,  111,  370,  108,  108,  108,
      253,  253,  253,  253,  253,  253,  389,  390,  400,  399,

      395,  108,  108,  391,  397,  398,  108,  392,  108,  402,
      401,  108,  404,  393,  108,  108,  394,  108,  108,  403,
      108,  108,  108,  108,  108,  108,  108,  108,  408,  405,
      412,  406,  409,  414,  407,  413,  415,  108,  410,  108,
      411,  416,  419,  417,  108,  418,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  451,  108,
      452,  108,  108,  420,  421,  108,  107,  108,  108,  453,
      422,  108,  111,  107,  108,  454,  108,  423,  455,  111,
      458,  425,  426,  108,  467,  460,  462,  108,  427,  108,
      108,  428,  437,  438,  424,  443,  446,  429,  433,  447,

      430,  432,  434,  435,  431,  436,  439,  440,  441,  459,
      444,  448,  461,  442,  445,  449,  449,  449,  108,  108,
      108,  108,  108,  108,  449,  449,  449,  449,  449,  449,
      463,  464,  465,  108,  108,  472,  108,  108,  473,  108,
      108,  108,  108,  469,  108,  108,  466,  468,  478,  477,
      480,  108,  108,  108,  108,  108,  108,  108,  108,  479,
      484,  487,  485,  108,  108,  108,  108,  481,  470,  488,
      108,  108,  108,  108,  474,  489,  476,  475,  108,  108,
      471,  108,  482,  108,  108,  108,  108,  108,  108,  108,
      486,  108,  108,  108,  108,  108,  108,  483,   75,  108,

       75,   75,   75,   83,  108,   83,   83,   83,   99,   99,
       99,   99,   99,  111,  111,  111,  232,  108,  232,  232,
      232,  235,  108,  235,  235,  235,  238,  108,  238,  238,
      238,  241,  108,  241,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  457,  456,
      450,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,

      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  383,  382,  381,  380,  379,  378,
      377,  375,  374,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  100,
      252,  251,  250,  249,  242,  240,  239,  236,  234,  233,
      231,  108,  108,  108,  108,  108,  108,  103,  100,   84,
       76,   74,  490,    3,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490
    } ;

static yyconst flex_int16_t yy_chk[1176] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    9,    5,   11,   11,   26,   26,   28,   28,
       29,   29,   10,   10,   10,   49,   39,  139,    9,    9,

        9,   10,   10,   10,   10,   10,   10,    9,    9,    9,
        9,    9,    9,   12,  139,   49,   35,   39,  493,   39,
       36,  115,   35,   12,   12,   12,   20,   35,   20,   20,
       36,  115,   12,   12,   12,   12,   12,   12,   43,   20,
       22,   22,   22,   48,   20,   36,   43,  127,   43,   22,
       22,   22,   22,   22,   22,   70,   22,   48,   43,   69,
       44,   37,   62,   23,   23,   23,  127,   37,   43,   80,
       80,   20,   23,   23,   23,   23,   23,   23,   37,   23,
       24,   24,   24,   44,   22,   44,   44,  106,  106,   24,
       24,   24,   24,   24,   24,   32,   24,   32,   22,   62,

      107,   69,   70,   32,   62,  133,  107,   23,   41,   59,
       32,   33,   33,   33,   33,   33,  113,   41,   41,   33,
       33,   54,   41,   33,   24,   30,   30,   30,   30,   33,
      113,  133,   33,   41,   30,   30,   30,   30,   30,   30,
       34,   30,   73,   59,   73,   30,   34,   30,   38,  114,
      167,   34,   30,   59,   34,   34,   55,   54,  114,   38,
       34,  167,  117,   54,  489,   45,   38,   38,  117,   30,
       31,   31,   31,   31,   53,   45,   38,   38,   46,   31,
       31,   31,   31,   31,   31,   45,   31,   31,   46,   47,
       55,   45,   55,   56,  118,   46,   47,   47,  134,   47,

       57,   46,   46,  123,   55,   60,   47,   64,   61,  123,
       47,   53,   47,   53,   31,   47,   65,  119,   53,  118,
       53,  134,  486,  119,   66,   53,  119,   56,   56,   67,
       56,   56,  132,  109,  109,   56,   56,  110,   56,  109,
       68,  132,   57,   64,   56,   64,   57,   56,  161,   57,
       60,   60,  150,  124,   64,   57,   61,  110,   61,  124,
       60,   60,   66,  110,   64,  484,   65,   67,   65,   65,
      150,   66,  161,   67,  166,   68,   68,   66,   68,   67,
       67,  122,  166,  122,   68,   78,   78,   78,   68,  122,
       68,  179,  153,   68,   78,   78,   78,   78,   78,   78,

       79,   79,   79,  135,  153,  160,   82,   82,   82,   79,
       79,   79,   79,   79,   79,   82,   82,   82,   82,   82,
       82,   87,  120,   87,   87,  120,  160,  216,  120,  179,
      136,  135,   87,   92,   92,   92,  136,  154,   87,  121,
      230,   87,   92,   92,   92,   92,   92,   92,  121,   92,
       93,   93,   93,  121,  154,  144,  121,  483,  154,   93,
       93,   93,   93,   93,   93,  141,   93,  158,  144,   94,
       94,   94,  144,  175,  141,  216,  145,   92,   94,   94,
       94,   94,   94,   94,  141,   94,   95,   95,   95,  145,
      230,  156,  158,  145,   93,   95,   95,   95,   95,   95,

       95,  172,   95,  156,  162,   98,   98,   98,  172,  175,
      175,  481,  165,   94,   98,   98,   98,   98,   98,   98,
      125,  177,  148,  125,  143,  157,  125,  168,  162,  162,
       95,  148,  143,  143,  157,  163,  148,  165,  143,  157,
      164,  163,  173,  163,  163,  169,  164,  171,  164,  164,
      174,  169,  168,  171,  176,  178,  181,  182,  183,  185,
      188,  184,  169,  177,  171,  190,  176,  173,  196,  195,
      197,  198,  206,  174,  222,  202,  201,  207,  217,  203,
      214,  263,  210,  218,  209,  221,  270,  212,  224,  236,
      236,  213,  178,  185,  229,  479,  188,  183,  184,  188,

      270,  182,  219,  184,  263,  184,  195,  220,  181,  206,
      222,  190,  201,  201,  206,  198,  202,  223,  201,  202,
      203,  196,  207,  203,  209,  197,  210,  212,  213,  217,
      210,  225,  214,  213,  218,  218,  219,  221,  219,  219,
      224,  220,  227,  220,  220,  228,  229,  254,  237,  237,
      237,  261,  257,  254,  259,  264,  223,  237,  237,  237,
      237,  237,  237,  255,  257,  225,  259,  262,  261,  255,
      269,  266,  478,  262,  275,  225,  227,  266,  264,  267,
      228,  253,  253,  253,  272,  267,  227,  274,  276,  279,
      253,  253,  253,  253,  253,  253,  268,  268,  276,  275,

      269,  277,  278,  268,  272,  274,  280,  268,  285,  278,
      277,  286,  279,  268,  287,  292,  268,  293,  289,  278,
      296,  294,  298,  319,  321,  314,  323,  325,  287,  280,
      294,  285,  289,  296,  286,  294,  298,  300,  292,  303,
      293,  298,  314,  300,  326,  303,  330,  331,  337,  335,
      345,  347,  338,  343,  354,  344,  350,  351,  379,  408,
      379,  384,  358,  319,  321,  361,  389,  372,  356,  379,
      323,  352,  389,  390,  396,  379,  398,  325,  379,  390,
      384,  330,  330,  437,  408,  396,  398,  438,  330,  397,
      391,  330,  345,  347,  326,  354,  358,  330,  337,  361,

      330,  335,  338,  343,  331,  344,  350,  351,  352,  391,
      356,  372,  397,  352,  356,  376,  376,  376,  402,  400,
      403,  401,  420,  409,  376,  376,  376,  376,  376,  376,
      400,  401,  402,  419,  427,  437,  448,  464,  438,  459,
      465,  466,  468,  419,  471,  473,  403,  409,  464,  459,
      466,  477,  480,  482,  485,  487,  488,  474,  472,  465,
      477,  485,  480,  470,  469,  467,  463,  468,  420,  487,
      462,  461,  460,  458,  448,  488,  457,  456,  447,  446,
      427,  445,  471,  444,  443,  442,  441,  440,  439,  436,
      482,  435,  434,  433,  432,  431,  430,  473,  491,  429,

      491,  491,  491,  492,  428,  492,  492,  492,  494,  494,
      494,  494,  494,  495,  495,  495,  496,  426,  496,  496,
      496,  497,  425,  497,  497,  497,  498,  424,  498,  498,
      498,  499,  423,  499,  422,  421,  418,  417,  416,  415,
      414,  413,  412,  411,  410,  407,  406,  405,  404,  399,
      395,  394,  393,  392,  388,  387,  386,  385,  383,  382,
      378,  373,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  360,  359,  357,  355,  353,  349,  348,  346,
      342,  341,  340,  339,  336,  334,  333,  332,  329,  328,
      327,  324,  322,  320,  317,  316,  315,  313,  312,  311,

      310,  309,  308,  307,  306,  305,  304,  302,  301,  299,
      297,  295,  291,  290,  288,  284,  283,  282,  281,  273,
      271,  265,  260,  258,  252,  251,  250,  249,  245,  242,
      238,  235,  232,  226,  215,  211,  208,  205,  204,  200,
      199,  194,  193,  192,  191,  189,  187,  186,  180,  170,
      159,  155,  152,  151,  149,  147,  146,  142,  140,  138,
      137,  131,  130,  129,  128,  126,  116,  112,  111,   99,
       91,   90,   89,   88,   86,   84,   83,   77,   76,   75,
       72,   71,   63,   58,   50,   42,   40,   27,   25,   13,
        8,    7,    3,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"

#include <stdio.h>
#include <string.h>


#include "grammar.h"


/* Externally defined functions used here */
extern void fatalError(const char *str);


/* Declarations of locally defined functions */
void reset_lexer();
int from_binary(const char * s);


/*****************************/
/* Locally defined functions */
void reset_lexer() { YY_FLUSH_BUFFER;  yylineno = 1; }

int from_binary(const char * s) {
 char aux[60];
 
  if (strlen(s) > 59) { fatalError("Binary is too long"); }  
  strncpy(aux,s,strlen(s)); aux[strlen(s)] = 0x0;
  if (aux[strlen(aux)-1] == 'B' || aux[strlen(aux)-1] == 'b') {
     aux[strlen(aux)-1] = 0x0;
  }
  return (int) strtol(aux, NULL, 2);

}

int from_hexa(const char * s) {
 char aux[60];

  if (strlen(s) > 59) { fatalError("Hexadecimal number is too long"); }   
  strncpy(aux,s,strlen(s)); aux[strlen(s)] = 0x0;
  if (aux[strlen(aux)-1] == 'H' || aux[strlen(aux)-1] == 'h') {
     aux[strlen(aux)-1] = 0x0;
  }
  return (int) strtol(aux, NULL, 16);

}


#define YY_NO_INPUT 1
#line 922 "lex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 53 "lex.l"

#line 1140 "lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 491 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1094 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 54 "lex.l"
{ return NEWLINE; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 55 "lex.l"
{  return NEWLINE; } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "lex.l"
/* eat up whitespace */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "lex.l"
{ yylval.normal = yytext[1]; return CHAR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "lex.l"
{ yylval.normal = yytext[1]; return CHAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "lex.l"
{  strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-2]=0x0;return STRING; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "lex.l"
{  strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-2]=0x0;return STRING; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "lex.l"
{ return DEFB; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "lex.l"
{ return TITLE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "lex.l"
{ return TITLE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "lex.l"
{ return TITLE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "lex.l"
{ return TITLE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "lex.l"
{ return FNAME; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "lex.l"
{ return IF; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "lex.l"
{ return IFDEF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "lex.l"
{ return IFNDEF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "lex.l"
{ return ENDIF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "lex.l"
{ return NEQUAL;  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "lex.l"
{ return NEQUAL;  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "lex.l"
{ return EQUAL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "lex.l"
{ return GREATEREQ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "lex.l"
{ return GREATEREQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "lex.l"
{ return GREATERTHAN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "lex.l"
{ return GREATERTHAN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "lex.l"
{ return LESSTHAN;    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "lex.l"
{ return LESSEQ; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "lex.l"
{ return LESSTHAN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "lex.l"
{ return LESSEQ; } 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "lex.l"
{ return ORG; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "lex.l"
{ return EQU;  }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "lex.l"
{ return DEFB; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "lex.l"
{ return DEFS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "lex.l"
{ return DEFW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "lex.l"
{ return DEFB; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "lex.l"
{ return DEFD; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lex.l"
{ return DEFB; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "lex.l"
{ return DEFB; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "lex.l"
{ return DEFD; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "lex.l"
{ return DEFS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "lex.l"
{ return DEFW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "lex.l"
{ return DEFINED; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "lex.l"
{ return DEFINED; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "lex.l"
{ return DEFB; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 97 "lex.l"
{ return DEFB; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 98 "lex.l"
{ return DEFS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "lex.l"
{ return DEFS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "lex.l"
{ return DEFB; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "lex.l"
{ return DEFB; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "lex.l"
{ return DEFW; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "lex.l"
{ return DEFW; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "lex.l"
{ return DEFC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "lex.l"
{ return DEFC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "lex.l"
{ return DEFB; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "lex.l"
{ return DEFB; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "lex.l"
{ return DEFS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "lex.l"
{ return DEFS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "lex.l"
{ return DEFB; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "lex.l"
{ return DEFB; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "lex.l"
{ return DEFW; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "lex.l"
{ return DEFW; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "lex.l"
{ return DEFD; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "lex.l"
{ return DEFD; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "lex.l"
{ return ERROR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "lex.l"
{ return INCLUDE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "lex.l"
{ return INCLUDEBIN;  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "lex.l"
{ return INCLUDEBIN;  }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 120 "lex.l"
{ return NOLIST; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "lex.l"
{ return NOLIST; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 122 "lex.l"
{ return LIMIT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 123 "lex.l"
{ return LIMIT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "lex.l"
{ return ALIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "lex.l"
{ return ALIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "lex.l"
{ return DJNZ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 127 "lex.l"
{ return DJNZ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "lex.l"
{ return ASEG; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "lex.l"
{ return ASEG; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "lex.l"
{ return CALL; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "lex.l"
{ return CALL; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "lex.l"
{ return OTDR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "lex.l"
{ return OTDR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "lex.l"
{ return OTIR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "lex.l"
{ return OTIR; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "lex.l"
{ return OUTI; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "lex.l"
{ return OUTI; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "lex.l"
{ return OUTD; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "lex.l"
{ return OUTD; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "lex.l"
{ return INDR; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "lex.l"
{ return INDR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "lex.l"
{ return CPDR; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "lex.l"
{ return CPDR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "lex.l"
{ return CPIR; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "lex.l"
{ return CPIR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "lex.l"
{ return INIR; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "lex.l"
{ return INIR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "lex.l"
{ return HALT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "lex.l"
{ return HALT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "lex.l"
{ return LDDR; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "lex.l"
{ return LDDR; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "lex.l"
{ return LDIR; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "lex.l"
{ return LDIR; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "lex.l"
{ return PUSH; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "lex.l"
{ return PUSH; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 156 "lex.l"
{ return RETI; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "lex.l"
{ return RETI; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "lex.l"
{ return RETN; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "lex.l"
{ return RETN; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "lex.l"
{ return RLCA; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 161 "lex.l"
{ return RLCA; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 162 "lex.l"
{ return RRCA; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 163 "lex.l"
{ return RRCA; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 164 "lex.l"
{ return DEC; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 165 "lex.l"
{ return DEC; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 166 "lex.l"
{ return END; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 167 "lex.l"
{ return END; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 168 "lex.l"
{ return ORG; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 169 "lex.l"
{ return ORG; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 170 "lex.l"
{ return EQU; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 171 "lex.l"
{ return EQU; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 172 "lex.l"
{ return IYH; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 173 "lex.l"
{ return IYH; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 174 "lex.l"
{ return IYL; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 175 "lex.l"
{ return IYL; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 176 "lex.l"
{ return IXH; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 177 "lex.l"
{ return IXH; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 178 "lex.l"
{ return IXL; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 179 "lex.l"
{ return IXL; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 180 "lex.l"
{ return SUB; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 181 "lex.l"
{ return SUB; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 182 "lex.l"
{ return SRL; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 183 "lex.l"
{ return SRL; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 184 "lex.l"
{ return SRA; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 185 "lex.l"
{ return SRA; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 186 "lex.l"
{ return SLA; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 187 "lex.l"
{ return SLA; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 188 "lex.l"
{ return SLL; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 189 "lex.l"
{ return SLL; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 190 "lex.l"
{ return SET; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 191 "lex.l"
{ return SET; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 192 "lex.l"
{ return SCF; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 193 "lex.l"
{ return SCF; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 194 "lex.l"
{ return SBC; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 195 "lex.l"
{ return SBC; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 196 "lex.l"
{ return RST; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 197 "lex.l"
{ return RST; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 198 "lex.l"
{ return RRD; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 199 "lex.l"
{ return RRD; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 200 "lex.l"
{ return RRA; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 201 "lex.l"
{ return RRA; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 202 "lex.l"
{ return RRC; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 203 "lex.l"
{ return RRC; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 204 "lex.l"
{ return RLA; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 205 "lex.l"
{ return RLA; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 206 "lex.l"
{ return RLC; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 207 "lex.l"
{ return RLC; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 208 "lex.l"
{ return RLD; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 209 "lex.l"
{ return RLD; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 210 "lex.l"
{ return POP; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 211 "lex.l"
{ return POP; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 212 "lex.l"
{ return CPD; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 213 "lex.l"
{ return CPD; }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 214 "lex.l"
{ return CPI; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 215 "lex.l"
{ return CPI; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 216 "lex.l"
{ return LDI; }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 217 "lex.l"
{ return LDI; }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 218 "lex.l"
{ return LDD; }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 219 "lex.l"
{ return LDD; }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 220 "lex.l"
{ return CPL; }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 221 "lex.l"
{ return CPL; }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 222 "lex.l"
{ return DAA; }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 223 "lex.l"
{ return DAA; }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 224 "lex.l"
{ return OUT; }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 225 "lex.l"
{ return OUT; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 226 "lex.l"
{ return AND; }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 227 "lex.l"
{ return AND; }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 228 "lex.l"
{ return ADC; }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 229 "lex.l"
{ return ADC; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 230 "lex.l"
{ return ADD; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 231 "lex.l"
{ return ADD; }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 232 "lex.l"
{ return BIT; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 233 "lex.l"
{ return BIT; }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 234 "lex.l"
{ return CCF; }
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 235 "lex.l"
{ return CCF; }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 236 "lex.l"
{ return RET; }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 237 "lex.l"
{ return RET; }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 238 "lex.l"
{ return EXX; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 239 "lex.l"
{ return EXX; }
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 240 "lex.l"
{ return XOR; }
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 241 "lex.l"
{ return XOR; }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 242 "lex.l"
{ return INC; }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 243 "lex.l"
{ return INC; }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 244 "lex.l"
{ return IND; }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 245 "lex.l"
{ return IND; }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 246 "lex.l"
{ return INI; }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 247 "lex.l"
{ return INI; }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 248 "lex.l"
{ return NEG; }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 249 "lex.l"
{ return NEG; }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 250 "lex.l"
{ return NOP; }
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 251 "lex.l"
{ return NOP; }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 252 "lex.l"
{ return RES; }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 253 "lex.l"
{ return RES; }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 254 "lex.l"
{ return AFPLUS; }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 255 "lex.l"
{ return AFPLUS; }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 256 "lex.l"
{ return RL; }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 257 "lex.l"
{ return RL; }
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 258 "lex.l"
{ return RR; }
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 259 "lex.l"
{ return RR; }
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 260 "lex.l"
{ return LD; }
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 261 "lex.l"
{ return LD; }
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 262 "lex.l"
{ return OR; }
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 263 "lex.l"
{ return OR; }
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 264 "lex.l"
{ return JP; }
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 265 "lex.l"
{ return JP; }
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 266 "lex.l"
{ return JR; }
	YY_BREAK
case 214:
YY_RULE_SETUP
#line 267 "lex.l"
{ return JR; }
	YY_BREAK
case 215:
YY_RULE_SETUP
#line 268 "lex.l"
{ return AF; }
	YY_BREAK
case 216:
YY_RULE_SETUP
#line 269 "lex.l"
{ return AF; }
	YY_BREAK
case 217:
YY_RULE_SETUP
#line 270 "lex.l"
{ return BC; }
	YY_BREAK
case 218:
YY_RULE_SETUP
#line 271 "lex.l"
{ return BC; }
	YY_BREAK
case 219:
YY_RULE_SETUP
#line 272 "lex.l"
{ return DE; }
	YY_BREAK
case 220:
YY_RULE_SETUP
#line 273 "lex.l"
{ return DE; }
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 274 "lex.l"
{ return HL; }
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 275 "lex.l"
{ return HL; }
	YY_BREAK
case 223:
YY_RULE_SETUP
#line 276 "lex.l"
{ return SP; }
	YY_BREAK
case 224:
YY_RULE_SETUP
#line 277 "lex.l"
{ return SP; }
	YY_BREAK
case 225:
YY_RULE_SETUP
#line 278 "lex.l"
{ return IX; }
	YY_BREAK
case 226:
YY_RULE_SETUP
#line 279 "lex.l"
{ return IX; }
	YY_BREAK
case 227:
YY_RULE_SETUP
#line 280 "lex.l"
{ return IY; }
	YY_BREAK
case 228:
YY_RULE_SETUP
#line 281 "lex.l"
{ return IY; }
	YY_BREAK
case 229:
YY_RULE_SETUP
#line 282 "lex.l"
{ return DI; }
	YY_BREAK
case 230:
YY_RULE_SETUP
#line 283 "lex.l"
{ return DI; }
	YY_BREAK
case 231:
YY_RULE_SETUP
#line 284 "lex.l"
{ return EI; }
	YY_BREAK
case 232:
YY_RULE_SETUP
#line 285 "lex.l"
{ return EI; }
	YY_BREAK
case 233:
YY_RULE_SETUP
#line 286 "lex.l"
{ return EX; }
	YY_BREAK
case 234:
YY_RULE_SETUP
#line 287 "lex.l"
{ return EX; }
	YY_BREAK
case 235:
YY_RULE_SETUP
#line 288 "lex.l"
{ return CP; }
	YY_BREAK
case 236:
YY_RULE_SETUP
#line 289 "lex.l"
{ return CP; }
	YY_BREAK
case 237:
YY_RULE_SETUP
#line 290 "lex.l"
{ return NZ; }
	YY_BREAK
case 238:
YY_RULE_SETUP
#line 291 "lex.l"
{ return NZ; }
	YY_BREAK
case 239:
YY_RULE_SETUP
#line 292 "lex.l"
{ return NC; }
	YY_BREAK
case 240:
YY_RULE_SETUP
#line 293 "lex.l"
{ return NC; }
	YY_BREAK
case 241:
YY_RULE_SETUP
#line 294 "lex.l"
{ return PO; }
	YY_BREAK
case 242:
YY_RULE_SETUP
#line 295 "lex.l"
{ return PO; }
	YY_BREAK
case 243:
YY_RULE_SETUP
#line 296 "lex.l"
{ return PE; }
	YY_BREAK
case 244:
YY_RULE_SETUP
#line 297 "lex.l"
{ return PE; }
	YY_BREAK
case 245:
YY_RULE_SETUP
#line 298 "lex.l"
{ return IM; }
	YY_BREAK
case 246:
YY_RULE_SETUP
#line 299 "lex.l"
{ return IM; }
	YY_BREAK
case 247:
YY_RULE_SETUP
#line 300 "lex.l"
{ return IN; }
	YY_BREAK
case 248:
YY_RULE_SETUP
#line 301 "lex.l"
{ return IN; }
	YY_BREAK
case 249:
YY_RULE_SETUP
#line 302 "lex.l"
{ return Z; }
	YY_BREAK
case 250:
YY_RULE_SETUP
#line 303 "lex.l"
{ return Z; }
	YY_BREAK
case 251:
YY_RULE_SETUP
#line 304 "lex.l"
{ return P; }
	YY_BREAK
case 252:
YY_RULE_SETUP
#line 305 "lex.l"
{ return P; }
	YY_BREAK
case 253:
YY_RULE_SETUP
#line 306 "lex.l"
{ return M; }
	YY_BREAK
case 254:
YY_RULE_SETUP
#line 307 "lex.l"
{ return M; }
	YY_BREAK
case 255:
YY_RULE_SETUP
#line 308 "lex.l"
{ return A; }
	YY_BREAK
case 256:
YY_RULE_SETUP
#line 309 "lex.l"
{ return A; }
	YY_BREAK
case 257:
YY_RULE_SETUP
#line 310 "lex.l"
{ return B; }
	YY_BREAK
case 258:
YY_RULE_SETUP
#line 311 "lex.l"
{ return B; }
	YY_BREAK
case 259:
YY_RULE_SETUP
#line 312 "lex.l"
{ return C; }
	YY_BREAK
case 260:
YY_RULE_SETUP
#line 313 "lex.l"
{ return C; }
	YY_BREAK
case 261:
YY_RULE_SETUP
#line 314 "lex.l"
{ return D; }
	YY_BREAK
case 262:
YY_RULE_SETUP
#line 315 "lex.l"
{ return D; }
	YY_BREAK
case 263:
YY_RULE_SETUP
#line 316 "lex.l"
{ return E; }
	YY_BREAK
case 264:
YY_RULE_SETUP
#line 317 "lex.l"
{ return E; }
	YY_BREAK
case 265:
YY_RULE_SETUP
#line 318 "lex.l"
{ return H; }
	YY_BREAK
case 266:
YY_RULE_SETUP
#line 319 "lex.l"
{ return H; }
	YY_BREAK
case 267:
YY_RULE_SETUP
#line 320 "lex.l"
{ return L; }
	YY_BREAK
case 268:
YY_RULE_SETUP
#line 321 "lex.l"
{ return L; }
	YY_BREAK
case 269:
YY_RULE_SETUP
#line 322 "lex.l"
{ return R; }
	YY_BREAK
case 270:
YY_RULE_SETUP
#line 323 "lex.l"
{ return R; }
	YY_BREAK
case 271:
YY_RULE_SETUP
#line 324 "lex.l"
{ return I; }
	YY_BREAK
case 272:
YY_RULE_SETUP
#line 325 "lex.l"
{ return I; }
	YY_BREAK
case 273:
YY_RULE_SETUP
#line 326 "lex.l"
{ return F; }
	YY_BREAK
case 274:
YY_RULE_SETUP
#line 327 "lex.l"
{ return F; }
	YY_BREAK
case 275:
YY_RULE_SETUP
#line 328 "lex.l"
{ strncpy(yylval.literal,yytext,strlen(yytext)); yylval.literal[strlen(yytext)-1]=0x0;return LABEL; }
	YY_BREAK
case 276:
YY_RULE_SETUP
#line 329 "lex.l"
{ strncpy(yylval.literal,yytext+1,strlen(yytext)-1); yylval.literal[strlen(yytext)-1]=0x0;return LABEL; }
	YY_BREAK
case 277:
YY_RULE_SETUP
#line 330 "lex.l"
{ yylval.normal = from_binary(yytext+1); return INTEGER; }
	YY_BREAK
case 278:
YY_RULE_SETUP
#line 331 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 279:
YY_RULE_SETUP
#line 332 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 280:
YY_RULE_SETUP
#line 333 "lex.l"
{ yylval.normal = from_hexa(yytext+1); return INTEGER; }
	YY_BREAK
case 281:
YY_RULE_SETUP
#line 334 "lex.l"
{ yylval.normal = from_hexa(yytext); return INTEGER;  }
	YY_BREAK
case 282:
YY_RULE_SETUP
#line 335 "lex.l"
{ yylval.normal = from_hexa(yytext); return INTEGER;  }
	YY_BREAK
case 283:
YY_RULE_SETUP
#line 336 "lex.l"
{ strcpy(yylval.literal,yytext); return LITERAL; }
	YY_BREAK
case 284:
YY_RULE_SETUP
#line 337 "lex.l"
{ yylval.normal = atoi(yytext); return INTEGER; }
	YY_BREAK
case 285:
YY_RULE_SETUP
#line 338 "lex.l"
{ yylval.normal = from_binary(yytext); return INTEGER;  }
	YY_BREAK
case 286:
YY_RULE_SETUP
#line 339 "lex.l"
{ yylval.normal = from_binary(yytext+1); return INTEGER;  }
	YY_BREAK
case 287:
YY_RULE_SETUP
#line 340 "lex.l"
{ yylval.normal = from_hexa(yytext+2); return INTEGER; }
	YY_BREAK
case 288:
/* rule 288 can match eol */
YY_RULE_SETUP
#line 341 "lex.l"
{ return NEWLINE; }
	YY_BREAK
case 289:
YY_RULE_SETUP
#line 342 "lex.l"
{ return MINUS; }
	YY_BREAK
case 290:
YY_RULE_SETUP
#line 343 "lex.l"
{ return COMMA; }
	YY_BREAK
case 291:
YY_RULE_SETUP
#line 344 "lex.l"
{ return PARLEFT; }
	YY_BREAK
case 292:
YY_RULE_SETUP
#line 345 "lex.l"
{ return PARRIGHT; }
	YY_BREAK
case 293:
YY_RULE_SETUP
#line 346 "lex.l"
{ return PARLEFT; }
	YY_BREAK
case 294:
YY_RULE_SETUP
#line 347 "lex.l"
{ return PARRIGHT; }
	YY_BREAK
case 295:
YY_RULE_SETUP
#line 348 "lex.l"
{ return PLUS; }
	YY_BREAK
case 296:
YY_RULE_SETUP
#line 349 "lex.l"
{ return MULT; }
	YY_BREAK
case 297:
YY_RULE_SETUP
#line 350 "lex.l"
{ return BITAND; }
	YY_BREAK
case 298:
YY_RULE_SETUP
#line 351 "lex.l"
{ return AND; }
	YY_BREAK
case 299:
YY_RULE_SETUP
#line 352 "lex.l"
{ return BITOR;  }
	YY_BREAK
case 300:
YY_RULE_SETUP
#line 353 "lex.l"
{ return OR;  }
	YY_BREAK
case 301:
YY_RULE_SETUP
#line 354 "lex.l"
{ return OPSHLF; }
	YY_BREAK
case 302:
YY_RULE_SETUP
#line 355 "lex.l"
{ return OPSHRT; }
	YY_BREAK
case 303:
YY_RULE_SETUP
#line 356 "lex.l"
{ return DIVIDE; }
	YY_BREAK
case 304:
YY_RULE_SETUP
#line 357 "lex.l"
{ return DOLAR;  }
	YY_BREAK
case 305:
YY_RULE_SETUP
#line 358 "lex.l"
{ return EQUAL;  }
	YY_BREAK
case 306:
YY_RULE_SETUP
#line 359 "lex.l"
{ return EXCLAMATION; }
	YY_BREAK
case 307:
YY_RULE_SETUP
#line 361 "lex.l"
ECHO;
	YY_BREAK
#line 2735 "lex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 491 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 491 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 490);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 361 "lex.l"




